### ISSUE TITLE
UnicodeDecodeError running BART on Windows

### ISSUE THREAD

**Issue by cmaximino** [psychopy/psychopy#1674] opened 2018-01-16 22:15 UTC
Good afternoon,
My student has been trying to run the BART demo on Psychopy 1.86, running on a machine with Windows 7, and has been bumping on an error when running the script. The script crashes after inserting subject data, with the following log:

pyo version 0.8.7 (uses single precision)
Traceback (most recent call last):
  File "C:\Users\Ayrk\Downloads\BART task\bart_lastrun.py", line 114, in <module>
    bang = sound.Sound("bang.wav")
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\sound\backend_pyo.py", line 287, in __init__
    init(rate=sampleRate)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\sound\backend_pyo.py", line 132, in init
    audioDriver, outputID = _bestDriver(devNames, devIDs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\sound\backend_pyo.py", line 27, in _bestDriver
    preferredDrivers = prefs.general['audioDriver']
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\configobj.py", line 563, in __getitem__
    new = [_check(entry) for entry in val]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 18: invalid continuation byte

As far as I understood, there is some problem with the sound driver. Is that it? How to fix it?

**Comment by peircej** [comment] 2018-01-19 21:22
I don't think he/she is running 1.86 (not released). Maybe 1.85.6 but could you check on that to be sure? The issue is probably that the machine is not in English locale and has an audio driver that has been given a name with a unicode character (like an umlaut). We've fixed a couple of related bugs that have been released but there was another one of these recently that only just got fixed.

**Comment by cmaximino** [comment] 2018-01-22 15:03
Good morning.
I can confirm that he's running 1.85.6 on a Windows machine, with a PT-BR
locale.

Caio Maximino

Em 19 de jan de 2018 18:22, "Jon Peirce" <notifications@github.com>
escreveu:

**Comment by Feulo** [comment] 2018-02-15 20:18
I'm having the same problem. I'm also running 1.85.6 version on a Windows 10 Machine.  Does anybody solved the problem?

**Comment by peircej** [comment] 2018-02-15 20:40
The problem has been solved in the repository code by @hsogo and will be fixed in the next (imminent) release

**Closed by peircej** 2018-02-15 20:40 UTC
