### ISSUE TITLE
syntax error prevents install from source

### ISSUE THREAD

**Issue by alex-asturias** [psychopy/psychopy#1003] opened 2015-11-17 19:55 UTC
I just tried installing from source and I had to edit psychopy-1.83.01/psychopy/demos/coder/iohub/elotouchscreen/run.py line 47 has an extra comma

**Comment by hoechenberger** [comment] 2015-11-20 12:26
This is a duplicate of #982 and has already been fixed.

**Closed** 2015-12-09 15:24 UTC
