### ISSUE TITLE
Is there a plan to support python3.8/above?

### ISSUE THREAD

**Issue by yaowang1111** [psychopy/psychopy#3253] opened 2020-10-27 15:46 UTC
Hi,

I'm wondering is there a plan to support python3.8 or above version?
Cause i want to use asyncio to do some network communication, and asyncio made big changes after py3.8.

I try to install psychopy using conda install -c conda-forge psychopy, the python installed for me is python3.8. 
However, when i import pyschopy in my script, an error occurs which is:
DLL load failed while importing lapack_lite

Thanks for help!

**Comment by peircej** [comment] 2020-11-17 18:02
As usual, the main issue here is that our dependencies aren't available yet. wxPython only provides wheels up to py3.7 and then we'd have various hardware libs that also need to update (eyetracker dlls etc). Once the dependencies exist I expect it will be easy for our own code to update

**Comment by peircej** [comment] 2020-11-19 20:45
I just ran PsychoPy from the repo on Py3.8 (from python.org) and it worked fine! I suspect the issue is actually to do with the conda packaging of lapack_lite (@hoechenberger might know more about that). 

@yaowang1111 could you give the full error trace please rather than the last line so we can confirm? 

I'm closing this for now but we can reopen if it looks like there is an issue in psychopy code that makes it 3.8 incompatible

**Closed by peircej** 2020-11-19 20:45 UTC
Labels: enhancement, standalone & packaging
