### ISSUE TITLE
window.size reports double actual size in Retina displays

### ISSUE THREAD

**Issue by jacob-lee** [psychopy/psychopy#2489] opened 2019-06-07 19:48 UTC
Window object is reporting double the actual size.

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
 
>>> import psychopy
>>> psychopy.__version__
'3.1.2'
>>> from psychopy import visual
>>> window = visual.Window(size=(2000,1000))
>>> window.size
array([4000, 2000])
>>> window.backend.win.size
array([4000, 2000])
>>> window.backend.win.winHandle
CocoaWindow(width=2000, height=1000)
```

Note, that it even doubles the default.

```python
>>> window = visual.Window() # Default should be (800, 600)
>>> window.size
array([1600, 1200])
>>> pprint.pprint(window.__dict__)
{'_closed': False,
 '_eventDispatchers': [],
 '_farClip': 100.0,
 '_frameTime': 7.285532688998501,
 '_haveShaders': True,
 '_hw_handle': 9435,
 '_initParams': ['allowGUI',
                 'allowStencil',
                 'args',
                 'autoLog',
                 'bitsMode',
                 'blendMode',
                 'color',
                 'colorSpace',
                 'fullscr',
                 'gamma',
                 'kwargs',
                 'lms',
                 'monitor',
                 'multiSample',
                 'name',
                 'numSamples',
                 'pos',
                 'screen',
                 'size',
                 'stereo',
                 'units',
                 'useFBO',
                 'useRetina',
                 'viewOri',
                 'viewPos',
                 'viewScale',
                 'waitBlanking',
                 'winType'],
 '_isFullScr': False,
 '_monitorFrameRate': 59.982483436507344,
 '_nearClip': 0.1,
 '_progFBOtoFrame': 4,
 '_progImageStim': 31,
 '_progSignedFrag': 7,
 '_progSignedTex': 13,
 '_progSignedTexFont': 1,
 '_progSignedTexMask': 16,
 '_progSignedTexMask1D': 19,
 '_projectionMatrix': array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32),
 '_shaders': {'imageStim': 31,
              'imageStim_adding': 34,
              'signedColor': 7,
              'signedColor_adding': 10,
              'signedTex': 13,
              'signedTexMask': 16,
              'signedTexMask1D': 19,
              'signedTexMask1D_adding': 28,
              'signedTexMask_adding': 25,
              'signedTex_adding': 22},
 '_toCall': [],
 '_toDraw': [],
 '_toDrawDepths': [],
 '_toLog': [],
 '_viewMatrix': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32),
 'allowGUI': True,
 'allowStencil': False,
 'autoLog': True,
 'backend': <psychopy.visual.backends.pygletbackend.PygletBackend object at 0x7fe6e80cfb00>,
 'bits': None,
 'blendMode': 'avg',
 'color': array([0., 0., 0.]),
 'colorSpace': 'rgb',
 'dkl_rgb': None,
 'frameClock': <psychopy.clock.Clock object at 0x7fe6f89f8dd8>,
 'frameIntervals': [],
 'frames': 11,
 'gamma': None,
 'glVendor': 'ati technologies inc.',
 'lastFrameT': 7.285532688998501,
 'lms_rgb': None,
 'monitor': <psychopy.monitors.calibTools.Monitor object at 0x7fe6e80cfa90>,
 'monitorFramePeriod': 0.016671533799672032,
 'movieFrames': [],
 'multiSample': False,
 'nDroppedFrames': 0,
 'name': 'window1',
 'numSamples': 2,
 'pos': [880.0, 420.0],
 'recordFrameIntervals': False,
 'recordFrameIntervalsJustTurnedOn': False,
 'refreshThreshold': 0.020005840559606438,
 'rgb': array([0., 0., 0.]),
 'scrDistCM': None,
 'scrWidthCM': None,
 'scrWidthPIX': None,
 'screen': 0,
 'size': array([1600, 1200]),
 'stereo': False,
 'units': 'norm',
 'useFBO': False,
 'useNativeGamma': True,
 'useRetina': True,
 'viewOri': 0.0,
 'viewPos': None,
 'viewScale': None,
 'waitBlanking': True,
 'winHandle': CocoaWindow(width=800, height=600),
 'winType': 'pyglet'}
```

**Comment by peircej** [comment] 2019-06-10 09:41
Almost certainly it means your using a retina mac display, where the actual number of screen pixels is higher than the number of 'equivalent' pixles at normal resolutions. See the discussion here: https://discourse.psychopy.org/t/understanding-the-retina-screen-scaling-of-stimuli/3798

The question is what's the best thing to do. Apple's approach is to provide a window that's the expected size, but then report the actual size as well. That's what we're currently doing, although I'm quite tempted to change that and simply treat a retina display as a high-resolution regular display

**Comment by peircej** [comment] 2019-06-10 09:42
The current behaviour is not a bug, however and (briefly) documented here: https://www.psychopy.org/api/visual/window.html
so I'm closing this for now

**Closed by peircej** 2019-06-10 09:42 UTC

**Comment by jacob-lee** [comment] 2019-06-10 17:16
I see. This issue came to my attention because I moved existing code to a new dev machine (and updated version of PsychoPy) and my code no longer worked as expected: the size of stimuli were too small by half. 

I am still not sure if everything is working as you intend; at least it no longer seems Window.size is a reliable interface with which to  scale stimuli appropriately. Some examples:

```python
from psychopy import visual
win = visual.Window(units="pix")
rect = visual.Rect(win=win, width=100, height=win.size[1]-1, lineColor="white")
rect.draw()
win.flip()
```

If `win.size[1]` was giving me the correct size, I should see the top and bottom lines of the rectangle. But I don't.

On the other hand, I do see the top and bottom of the rectangle if I do either:

```python
rect = visual.Rect(win=win, width=100, 
    height=win.winHandle.height-1, lineColor="white")
```

or

```python
 rect = visual.Rect(win=win, width=100, 
    height=win.size[1]-601, lineColor="white")
```

Similarly, if I want to draw a rectangle around a TextStim, when `units="height"`, my rectangle becomes too small:

```python
win = visual.Window(units="height")
text = visual.TextStim(win=win, text="Example Text")
b = text.boundingBox
rect = visual.Rect(win=win, width=b[0]/win.size[1], 
    height=b[1]/win.size[1], lineColor="white")
text.draw()
rect.draw()
win.flip()
```

I can fix it by doing: 

```python
rect = visual.Rect(win=win, width=b[0]/win.winHandle.height, 
    height=b[1]/win.winHandle.height, lineColor="white")
```

I'll have to check to see whether the object indicated by winHandle can be relied on to show the same interface across OS's.
