### ISSUE TITLE
Possible bug fix for reading rows as a variable

### ISSUE THREAD

**Issue by bpkst2** [psychopy/psychopy#881] opened 2015-03-24 22:12 UTC
I am a PsychoPy newbie, using the Builder (1.82.01) on a MacBook Pro (OS 10.9).  I am also using version 14.4.8 of Excel 2011.

Bug Description. I had a nested for-loop with the outer loop referring to a master file which defined the specific rows to be used in the inner for-loops.  The variable defined in the master file was: 

rows
0:4
4:8
8:12

For the first two sets of rows (0:4 and 4:8), the code ran fine, but when it reached 8:12, it generated the following error: 

 File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/data.py", line 1448, in importConditions
    elif len(selection)>0:
TypeError: object of type 'float' has no len()

One of the columns of the .csv output file correctly showed the rows for the first 8 trials, but then on the ninth trial, it displayed a mysterious fraction (.34166).   After some troubleshooting, I realized that it was treating 8:12 as a time unit and dividing that value by 24 hours.  (Incidentally, if you type in 8:12 into an excel cell, and convert it to text, it becomes .34166).  I made sure that the cell format in the master file was text and not time, but that didn't explain the problem.  I also tried different file types (.xlsx and .csv), but it didn't help.

Solution: To solve the problem, I tacked on zeros to each number so that they would not convert to time values (or to fractions).   For example, whereas 8:12 did not work, either 008:012 or 8:012 resulted in a properly running experiment.

Brian

**Comment by jeremygray** [comment] 2015-03-25 10:55
Glad you have a workaround. While this behavior was unexpected on your part, its not a PsychoPy bug. Its just how Excel works. My personal preference is to use a plain vanilla text editor, and save as .csv. I don't want the fancy formatting and Excel trying to be helpful, e.g., with auto-correction, time conversions, etc.

**Comment by peircej** [comment] 2015-03-25 11:33
oof, I'm going to blame excel for this one then, for converting your value into a ridiculous time format! Who even expresses time as "decimal fraction of the day"?! I imagine you could also have worked around by making the cell text with quotes? 
Technically we could insert something here that checked for a decimal in this location (in importConditions()) and assumed that this is what had gone wrong and recreate a 8:12 string. The problem is that if we did that and users accidentally provided a float then we would 'fix' it for them rather than having crash and they would find that even harder to debug.

With that in mind, I suggest we close this as 'not going to change'

**Comment by bpkst2** [comment] 2015-03-25 15:11
Thanks for the rapid feedback!  Jeremy, I'm not sure which text editor you have in mind; the TextEdit on my Mac does not seem to allow saving as a .csv format.  Also, in Excel, I saved the values as string format with .csv format, and that did not help.  I just now discovered that the problem can be solved by saving the .csv file with Matlab (using csvwrite), so that does suggest that Excel is the problem, as you rightly inferred.

Jon, putting the rows in quotes "8:12" also did not help; it gave the parsing error:

TypeError: importConditions() was given some `indices` but could not parse them.

I suspect that this annoying Excel issue might be a time sink for other PsychoPy newbies like myself. I'm therefore wondering if it might be helpful to add to the online instructions for "Selecting a subset of conditions" (http://www.psychopy.org/builder/flow.html).  The updated online material might say:
"$myIndices uses a variable that you’ve already created; when using Excel, be sure that values for this variable are not confusable with time values (e.g., 8:12 should be 8:012)".  Just a suggestion.

Brian

**Comment by jeremygray** [comment] 2015-03-25 15:41
Absolutely *any* text editor that can save as raw text will work (rich text .rtf and so on are NOT the same, they have extra glop in the files). On a mac, you can open a terminal and use `nano`

    nano conditions.csv

type in your text 

    a,b,c
    1,1,1
    2,2,2

and save the file, and you are done. You now have a conditions file with three columns, variables named `a`, `b`, and `c`

This works because nano writes out raw text, and you format the csv part by typing commas.

**Comment by bpkst2** [comment] 2015-03-25 15:45
Good to know, thanks Jeremy!  I wonder if Excel causes any other issues like the one that I encountered?  If so, maybe PsychoPy users should be persuaded to use a plain text editor as you suggest?

**Comment by jeremygray** [comment] 2015-03-25 15:48
There are issues with strings I believe, and I strongly suspect auto-correction could do bad things.

For small conditions files, you can use the built in mini-editor (ctrl-click in the conditions file dialog box to bring it up).

**Closed** 2015-03-26 11:00 UTC
