### ISSUE TITLE
import pyo fails in Windows (10) Standalone > 1.83.40

### ISSUE THREAD

**Issue by cjayb** [psychopy/psychopy#1434] opened 2017-06-12 13:10 UTC
There's a hint at this at the very bottom of [this discussion](https://discourse.psychopy.org/t/pyo-and-basic-import-problem/1339/13), but it was never followed up on.

I've done some testing, and can reproduce, under Windows 10:
* `import pyo` works on Standalone versions up to and including 1.83.04
* fails with the attached `DLL load`-failure on subsequent versions

I have _very_ little understanding about the inner workings of Windows-based systems, so pardon the ignorance, but... Could something have changed at the `exe` packaging stage after 1.83.04? Or is it simply a `pyo`-bug that's got into the latest releases of the standalone?

![pyo_error](https://user-images.githubusercontent.com/5610076/27035321-2c64c28e-4f81-11e7-9e76-f787aef2da2a.jpg)

**Comment by ddwagner** [comment] 2017-07-10 17:36
I'm having this issue with Windows standalone as well. Pyo import is fine with with 1.84.04 but fails with the same ImportError as above on 1.85.1 and 1.85.2.

**Comment by ddwagner** [comment] 2017-07-13 16:03
Adding to this thread, looks like the issue isn't psychopy related.  Imports with the latest (0.8.6) version of pyo fail with the same error when installed outside of psychopy standalone. Reverting the the prior version (0.8.5) fixes the DLL issue and seems to work fine. That doesn't help the current release of psychopy standalone, but for manual installs it seems to fix the DLL issue.  Perhaps psychopy standalone can be repackaged with the 0.8.5 release of pyo?

**Comment by peircej** [comment] 2017-08-11 09:28
OK, I'm currently installing pyo 1.8.5 on my windwos dev machine for the next release

**Comment by belangeo** [comment] 2017-08-23 22:32
It is fixed in Pyo sources. 0.8.7 is planned for the end of the month. Few other things to fix before packaging!

**Closed** 2021-08-04 14:34 UTC
Labels: needs upstream fix, platform windows, standalone & packaging
