### ISSUE TITLE
openpyxl and psychopy/data.py

### ISSUE THREAD

**Issue by terronymous-boosh** [psychopy/psychopy#1314] opened 2016-11-25 16:25 UTC
Just ran a manual install of 1.84.2, loaded all the pre-requisites and ran into the following error:
```
trialList=data.importConditions(u'SequentialPriming.xlsx'),
  File "C:\Python27\lib\site-packages\psychopy\data.py", line 2668, in importConditions
    raise ImportError('openpyxl is required for loading excel '
ImportError: openpyxl is required for loading excel format files, but it was not found.
```
it seems like as of godknowswhen openpyxl (version 2.4.1 on my machine) no longer has the method cell.get_column_letter, so instead you would need to change line 29 in data.py from

```from openpyxl.cell import get_column_letter```

to

```from openpyxl.utils import get_column_letter```

**Comment by hoechenberger** [comment] 2016-11-25 19:29
Could you try with latest master? I believe this was fixes in #1276 
Could be a dupe of #1274 then.

**Comment by terronymous-boosh** [comment] 2016-11-25 20:05
Thanks, sorry for not spotting that. Is there an easy way to install the
latest master using pip? Forgive my ignorance, I'm new to python.

Jon

**Comment by hoechenberger** [comment] 2016-11-25 20:33
```
pip install git+https://github.com/psychopy/psychopy
```
should to the trick. If you don't have git installed, you can try
```
pip install https://github.com/psychopy/psychopy/archive/master.zip
```

**Comment by hoechenberger** [comment] 2016-12-15 10:20
@terronymous-boosh, any news on this one?

**Comment by Soraltan** [comment] 2017-01-18 10:35
Hi, I had exactly the same error.

The suggested upgrade from the git reps did the trick.

**Comment by peircej** [comment] 2017-01-18 10:49
Thanks for confirming this is fixed in repos. Will be released very soon.

**Closed by peircej** 2017-01-18 10:49 UTC
Labels: bug, library, waiting for feedback
