### ISSUE TITLE
Uninstalling Windows standalone from custom install folder

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3505] opened 2021-02-02 13:24 UTC
The PsychoPy3 Windows uninstaller seems to assume that PsychoPy3 was installed in the default install location, even if it was installed to a different directory. For example, I installed to `D:\PsychoPy3` but the uninstaller tries to uninstall from `C:\Program Files\PsychoPy3`, which does not exist.

![uninstall_path_diff](https://user-images.githubusercontent.com/1795082/106605989-f7353c80-6537-11eb-8ee3-e61eb9101beb.png)

This results in PsychoPy3 uninstall not completing properly and the PsychoPy3 directory is not removed from the PC. However, the shortcuts are removed and the app is removed from the windows installed app list.

**Comment by peircej** [comment] 2021-02-04 10:32
Closing as duplicate of #3201 

As it stands I don't know how to fix this issue. The script that creates the NSIS installer *appears* to be set correctly (see below) https://github.com/psychopy/psychopy/blob/36db4db1c19018f6dbd6a37ea999337077b9af14/buildCompleteInstaller.nsi#L201

My best guess right now is that this is a bug in NSIS

**Closed by peircej** 2021-02-04 10:32 UTC
Labels: platform windows, standalone & packaging
