### ISSUE TITLE
from scipy.optimize import minpack2: module could not be found.

### ISSUE THREAD

**Issue by lavda897** [psychopy/psychopy#3252] opened 2020-10-27 14:31 UTC
Psychopy Not Working In My window.  The Error is 

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\lib\runpy.py", line 193, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "C:\Program Files\PsychoPy3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\psychopyApp.py
", line 104, in <module>
    main()
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\psychopyApp.py
", line 100, in main
    start_app()
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\psychopyApp.py
", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\_psychopyApp.p
y", line 24, in <module>
    from . import themes
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\themes\__init_
_.py", line 1, in <module>
    from ._themes import ThemeMixin, IconCache
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\themes\_themes
.py", line 16, in <module>
    from ...experiment import components
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\__init_
_.py", line 22, in <module>
    from .components import getInitVals, getComponents, getAllComponents
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\compone
nts\__init__.py", line 21, in <module>
    from ._base import BaseVisualComponent, BaseComponent
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\compone
nts\_base.py", line 21, in <module>
    from psychopy.alerts import alerttools
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\alerts\alerttools.
py", line 5, in <module>
    from psychopy.tools import monitorunittools
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\tools\monitorunitt
ools.py", line 15, in <module>
    from psychopy import monitors
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\monitors\__init__.
py", line 10, in <module>
    from .calibTools import *
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\monitors\calibTool
s.py", line 37, in <module>
    import scipy.optimize as optim
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\__init__.py"
, line 386, in <module>
    from .optimize import *
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\optimize.py"
, line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\linesearch.p
y", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: The specified module could not be found.

**Comment by peircej** [comment] 2020-10-27 14:44
Looks suspiciously similar to https://github.com/psychopy/psychopy/issues/3229

Could you confirm what PsychoPy version you're using and whether or not you have bitlocker encryption on your disk?

**Comment by lavda897** [comment] 2020-10-29 11:27
I am using latest version , in window 7 and 32bit

**Comment by lavda897** [comment] 2020-10-31 09:24
No anyone reply pls reply

**Comment by peircej** [comment] 2020-10-31 12:54
I haven't replied because I don't know what's wrong. For the record, when you say "latest version" you mean 2020.2.5, right? And do you have bitlocker encryption on the disk (which would be similar to the other post I pointed to)?

**Comment by lavda897** [comment] 2020-10-31 16:24
Yeah I have bitlocker in my disk my window is 7 ultimate...

**Comment by lavda897** [comment] 2020-11-01 05:49
Pls help this app not working pls help

**Comment by peircej** [comment] 2020-11-02 19:44
OK, well then I'm confident that this is a duplicate of issue #3229
I'm afraid I don't know how to solve it right now though - it appears that something about bitlocker causes a problem for scipy but that isn't a package we maintain, we merely provide a copy of it. I'm closing this issue in favour of #3229

**Closed by peircej** 2020-11-02 19:44 UTC
