### ISSUE TITLE
Text stim stop showing after so many trials

### ISSUE THREAD

**Issue by Howchie** [psychopy/psychopy#897] opened 2015-05-06 03:31 UTC
Working with latest version (1.82.01) on Windows 7 in builder view with some custom code, presenting two text stimuli and collecting a text response. All words come from a stimulus conditions file. Experiment works fine with small number of trials (48), but when using full length (480) crashes after about 130 trials with following message:
```python
Traceback (most recent call last):
  File "C:\Users\c3145114\Dropbox\PhD\Intersection in Memory\PsycoPy\SFT_Intersection\Final_SFT_Intersection_lastrun.py", line 2182, in <module>
    win.flip()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.82.01-py2.7.egg\psychopy\visual\window.py", line 539, in flip
    thisStim.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.82.01-py2.7.egg\psychopy\visual\text.py", line 591, in draw
    self._pygletTextObj.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\font\__init__.py", line 565, in draw
    self._layout.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\text\layout.py", line 852, in draw
    self.batch.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 544, in draw
    func()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 476, in <lambda>
    (lambda d, m: lambda: d.draw(m))(domain, mode))
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\vertexdomain.py", line 313, in draw
    glDrawArrays(mode, starts[0], sizes[0])
WindowsError: exception: access violation writing 0x00000004
```

**Comment by mgiammarco13** [comment] 2015-10-01 20:34
Hi,

I've run into the exact same issue using the coder and am wondering if you've found a solution? 
One thing I've done is changed the way I've set the text in the text stimuli.

originally I used "setText", but have switched to "._pygletTextObj.text= " but am still running into glitches

Thanks!

**Comment by jeremygray** [comment] 2015-10-12 03:01
This might be related to #973.

**Comment by hoechenberger** [comment] 2016-10-13 16:35
Appears indeed to be a dupe of #973, closing.

**Closed by hoechenberger** 2016-10-13 16:35 UTC
