### ISSUE TITLE
Program Runs very slowly 

### ISSUE THREAD

**Issue by bethjeff167** [psychopy/psychopy#1679] opened 2018-01-18 15:22 UTC
9.0056 ERROR returned with avbin.dll failed to load written. It says to try importing psychopy.visual. Where would I find this and how would I import it? Would this be likely to speed up the run speed of the experiment? The start process is very smooth but then trial intervals are 2 seconds but last for about 30 seconds (perhaps due to a low frame rate). Please advise me as to any suggestions you may have. Thanks!!!

**Comment by peircej** [comment] 2018-01-18 15:47
I'm sure avbin is not the problem, but can't tell from this what the problem is. It's most likely something to do with your study construction though so I'm closing this issue. Discourse forum is the place to discuss problems with experiments. github is really just for fixing actual bugs in the program
cheers,
Jon

**Closed by peircej** 2018-01-18 15:47 UTC
