### ISSUE TITLE
Users should be able to add more than one joystick component

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2150] opened 2018-12-17 08:02 UTC
This was [brought up](https://github.com/psychopy/psychopy/pull/2068#issuecomment-447684923) by @PanBartosz:

> My problem with this change is that does not work on my hardware/OS. Now you can only add one joystick component per experiment. For example now you cannot have two routines with joystick component (no joystick found error). I cannot figure out what is responsible for this change of behaviour.
> 
> EDIT. I compared old and new components and could not find any substantial differences in component initialization code. The problem is that when a second joystick is created pyglet library is throwing an exception (device already open) when psychopy is trying to get a device from pyglet. It makes sense but previously the code worked. I am really confused but tomorrow I will try to pin down the problem.
> 
> EDIT2: I checked old version (b11) and it has the same problem. I suppose that something changed in pyglet or other system libraries.

@m-macaskill responded:

> The issue @PanBartosz raises re being able to instantiate only one joystick component sounds similar to the same issues that have been addressed by @hoechenberger with his new syringe component? i.e. some components should only be initialised once, no matter how many times they appear in routines.

To which I replied:

> There's three potential issues here, as far as I can see. As @m-macaskill pointed out, I encountered similar problems when working on my pump component.
> 
> First potential issue is that each instance of the component adds their own `import` statements, so if you have two joystick components, all imports will be duplicated; for three components, imports will be triplicated (?!) etc. This can be easily addressed once #2145 is merged.
> 
> Second potential issue is that if you have multiple components trying to access the same device, there might naturally be resource conflicts. My solution with the pumps was to introduce a [module-global list of initialized devices](https://github.com/psychopy/psychopy/blob/77ab604c31303d79c9aaa7ab23ae2d6f6818d780/psychopy/hardware/qmix.py#L30), which could then be re-used.
> 
> This then leads to a third potential issue, which is that if we simply re-use the initialized devices across multiple components, we will experience race conditions as the the same `status` property gets updated by those different components. My workaround was to create [a thin "wrapper class"](https://github.com/psychopy/psychopy/blob/77ab604c31303d79c9aaa7ab23ae2d6f6818d780/psychopy/hardware/qmix.py#L290) with its very own `status`, and make the Builder component instantiate this wrapper, not the "actual" device class. So now, multiple components can use the same hardware device, but maintain separate `status`es.

**Comment by PanBartosz** [comment] 2018-12-18 09:03
The source of the problem is that during initialization of a joystick component pyglet `open()` method of Pyglet joystick object is called. Second `open()` throw DeviceOpenException (which is currently catched by try/except statements and "NO DEVICE FOUND" error is displayed to the user). Simplest solution to this problem seems to be calling `open()` at the beginning of the routine where a joystick component is added. I suppose that simple `try: joy.open()` would not introduce significant overhead during the experiment. What do you think about that?

**Comment by chrisgatwin** [comment] 2018-12-18 13:19
I haven't seen this problem on Mac or Windows, but it's probably better not good to relay on the OS not objecting to reopening devices. I have added a cache for open joysticks which should fix the problem for you. Let me know if it works for you and if so I will submit a pull request.
By the way, which OS are you having the problem with?

Replace your component/joystick/__init__.py with:
[joystick.zip](https://github.com/psychopy/psychopy/files/2690564/joystick.zip)

**Comment by peircej** [comment] 2021-08-17 15:33
I believe this is now fixed. Certainly there's a try...except around the joystick initialisation. Let's close and reopen if someone else finds it's still an issue

**Closed by peircej** 2021-08-17 15:33 UTC
Labels: 🌟 enhancement, 💻 app/ui
