### ISSUE TITLE
StandalonePsychoPy3_PY3-3.0.0b6-MacOS fails looking for /usr/local/opt/jpeg/lib/libjpeg.8.dylib

### ISSUE THREAD

**Issue by njvack** [psychopy/psychopy#1952] opened 2018-08-16 15:11 UTC
Starting b6 on my OS X (10.13.6) laptop fails with a "Psychopy3 Error" box.

When I use terminal and enter the package and run `Contents/MacOS/PsychyoPy3` I get a stack trace suggesting it's looking for `/usr/local/opt/jpeg/lib/libjpeg.8.dylib`. I have `/usr/local/opt/jpeg/lib/libjpeg.9.dylib` — maybe my homebrew is a bit newer?

I'm guessing, though, that a standalone package shouldn't rely on anything in /usr/local at all?

Logs and stack trace:

```
10:07:08 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:07:08 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:07:08 AM: Debug: Adding duplicate animation handler for '1' type
10:07:08 AM: Debug: Adding duplicate animation handler for '2' type
10:07:08 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:07:08 AM: Debug: Adding duplicate animation handler for '1' type
10:07:08 AM: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/__boot__.py", line 430, in <module>
    _run()
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/__boot__.py", line 409, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/psychopyApp.py", line 96, in <module>
    start_app()
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py", line 178, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py", line 212, in onInit
    from psychopy.app import coder, builder, dialogs
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/coder/__init__.py", line 9, in <module>
    from .coder import *  # pylint: disable=W0401
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/coder/coder.py", line 22, in <module>
    import psychopy.app.pavlovia_ui.menu
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/__init__.py", line 22, in <module>
    from . import menu, project, search, toolbar
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/toolbar.py", line 4, in <module>
    from .. import icons
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/icons.py", line 15, in <module>
    from PIL import Image
  File "/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /Users/njvack/Applications/PsychoPy3_PY3.app/Contents/Frameworks/libtiff.5.dylib
  Reason: image not found
2018-08-16 10:07:08.481 PsychoPy3[26987:5847798] PsychoPy3 Error
```

**Comment by peircej** [comment] 2018-08-16 15:19
Oh, OK, thanks. I know the root cause of this one but it's going to be a problem to fix:

I was previously using Pillow wheels for PIL, but that's currently not packaging correctly using py2app because of a compile flag that needs setting differently. I've asked them to update their build script but they seem hesitant. 
So I did `setup.py install` on the Pillow repository instead. Now build appears to succeed but I guess it's linking to my `libjpeg` rather than packaging a copy and then the user has a different copy to mine.

[sigh]

**Comment by njvack** [comment] 2018-08-16 15:25
I guess... I guess you could make your own Pillow wheel?

[sigh indeed]

**Comment by peircej** [comment] 2018-08-17 14:15
OK, I think I've got Pillow packaging with some ugly hacking (must remember not to update Pillow on my machine ever again though!). 3.0.0b7 currently being built

**Comment by njvack** [comment] 2018-08-17 16:44
Is there a way to test release builds on travis? I'm not saying "you should do this," I just don't know well enough how CI systems work...

**Comment by peircej** [comment] 2018-08-18 08:33
Not that I know. :-(
It's all manual which is exactly the problem

**Comment by peircej** [comment] 2018-08-18 08:55
But I'm planning to move to Jenkins for testing, on our own dedicated
slaves, where we'll have more control and can test on a wider range of
hardware

**Comment by peircej** [comment] 2018-08-20 12:08
Fairly confident this one is fixed in beta7

**Comment by jennifer-culbertson** [comment] 2018-08-21 09:44
I posted the redundant #1955, FYI this fix worked for me. Thanks!!

**Closed** 2018-08-21 10:01 UTC
Labels: needs upstream fix, platform mac, standalone & packaging
