### ISSUE TITLE
Massive sound delay and jitter using sounddevice backend

### ISSUE THREAD

**Issue by stfnrpplngr** [psychopy/psychopy#2065] opened 2018-10-15 12:24 UTC
I have already posted in the psychopy forum: [Massive Sound lag using PsychoPy](https://discourse.psychopy.org/t/massive-sound-lag-using-psychopy-windows-wasapi-for-external-sound-card/5530). I am stuck. Trying to activate exclusive mode as described in the [documentation of sounddevice](https://python-sounddevice.readthedocs.io/en/0.3.12/api.html#sounddevice.WasapiSettings) results in  `PaErrorCode -9996`.

```
Traceback (most recent call last):
  File "D:\Experimente\task1.py", line 85, in <module>
    sound_1 = sound.Sound('A', secs=-1, stereo=True)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 296, in __init__
    hamming=self.hamming)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 343, in setSound
    blockSize=self.blockSize)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 84, in getStream
    blockSize=blockSize)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 128, in _getStream
    device=defaultOutput)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 159, in __init__
    callback=self.callback)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\sounddevice.py", line 1373, in __init__
    **_remove_self(locals()))
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\sounddevice.py", line 779, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\sounddevice.py", line 2571, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening OutputStream: Invalid device [PaErrorCode -9996]
```

Do you have an idea on what is going wrong? Is there a bug? @peircej @mgeier @bastibe

**Comment by mgeier** [comment] 2018-10-15 17:39
AFAICT, the `play()` function isn't even used in PsychoPy. At least it doesn't appear in https://github.com/psychopy/psychopy/blob/b6f17b791170e33d839df1a4f21b0bd91b96406b/psychopy/sound/backend_sounddevice.py.

About the "Invalid device" error: this sounds similar: https://github.com/spatialaudio/python-sounddevice/issues/52.

**Comment by stfnrpplngr** [comment] 2018-10-24 12:58
I checked the sampling rates. In the Windows sound setting, system's default for the inbuilt speakers was 48000Hz. Changing that to 44100Hz did not change anything. For the Steinberg system the value cannot be changes but it preset to 44100Hz. But the field is grey, so I don't know whether this has any meaning. Its highest possible sampling rate is 192kHz.

In PsychoPy, I generate an 'A' with the inbuilt function `sound.Sound('A')`. Default sampling rate for this is 44100Hz. Playing around with different settings regarding driver and API, I ended up with various latencies but I was never as good as Psychtoolbox or Presentation. Since they are able to present a jitter-free acoustic stimulus I know it is possible. 

I reached the best timing using the ASIO drivers. Unfortunately, I did not manage (unitl now) to work in WASAPI exclusive mode. Interestingly there appears to be a wandering of the signal. The latency starts high and is reduced with every loop. Then, it jumps back to the high latency value repeating the process.

That is where it starts using ASIO:
![asio_wandering_sound_highlatency](https://user-images.githubusercontent.com/20129752/47431712-d8fb0680-d79c-11e8-9d8c-16e67c9c5bce.png)
After decreasing its latency with every loop, that is where it ends before jumping to the high latency again:
![asio_wandering_sound_lowlatency](https://user-images.githubusercontent.com/20129752/47431720-dd272400-d79c-11e8-8d67-a9ca449fc6e1.png)
It appears not as a simple random jitter, it is more systematic. Do you have any idea what could be the cause?

**Comment by stfnrpplngr** [comment] 2018-10-25 15:36
Today, I tried to present the sound directly via sounddevice, intentionally not using the PsychoPy backend. As a sound I generated a numpy sine wave:

```
import sounddevice as sd
sound1 = np.sin([np.arange(1, 3000), np.arange(1, 3000)]).transpose()
sd.default.device = 'UR22mkII Windows WASAPI'
wasapi_exclusive = sd.WasapiSettings(exclusive=True)
#sd.default.extra_settings = wasapi_exclusive
```
I commented the change of the default settings to `wasapi_exclusive`, because the leads to the `Invalid device [PaErrorCode -9996]`.
The sound is played using `sd.play(sound1)`. In the following pictures, you can see how the sound delay decreases before it jumps back. There is a corridor of about 10 ms.

![sound_delay_wasapi_sharedmode_start](https://user-images.githubusercontent.com/20129752/47512355-53e71e80-d87c-11e8-9470-fb2dea86a8ce.jpg)
![sound_delay_wasapi_sharedmode_intermediate](https://user-images.githubusercontent.com/20129752/47512366-58133c00-d87c-11e8-96e1-701c08e618f0.jpg)
![sound_delay_wasapi_sharedmode_stop](https://user-images.githubusercontent.com/20129752/47512373-5b0e2c80-d87c-11e8-9bbf-025da76d26f9.jpg)

**Comment by lindeloev** [comment] 2018-10-26 06:55
@stfnrpplngr, great that you are testing audio latency and jitter. This is certainly a point where PsychoPy could use some love, so feel free to test out more options and let us know if you find a solution.

Latency and jitter using the `sounddevice` module has been discussed a few times on Discourse:
 * https://discourse.psychopy.org/t/low-sound-latency-with-sounddevice-module-wdm-ks-driver/91 
 * https://discourse.psychopy.org/t/what-would-it-take-to-replace-pyo/1318

You could try out some of those tips and tricks. Some suggest setting up a stream, and then passing sounds to that rather than using `.play()`.  Also, the `sounddevice` documentation mention a `latency` argument.

As for the jitter you observe, it is likely caused by a buffer in your soundcard dispatching sounds every 10 ms or so on top of a latency of around 34 ms. Just guessing, though.

**Comment by stfnrpplngr** [comment] 2018-10-26 07:32
By setting up a stream, I solved the problem with our previous stimulation setup. But this necessitates using the coder for experiment conception. I was trying to solve it using the builder, so that other lab members could draft their experiments without extensive python proficiency.

**Comment by lindeloev** [comment] 2018-10-26 07:54
@stfnrpplngr, could you be a bit more specific about what you did to succeed and perhaps even post the trigger/waveform image? Perhaps the PsychoPy team could implement this in Builder. I know this doesn't solve your problems here and now, but it would be immensely useful information to help move PsychoPy forward in this respect.

As a temporary workaround, you can create the Python code in Builder by pressing F5; then replace the relevant sections with the streaming solution. This, of course, is a one-way street (it won't feed back into your Builder file), so just do it before data collection, when all other aspects of your experiment are settled.

**Comment by peircej** [comment] 2020-08-04 16:40
I'm closing this because the superior method is to use the psychtoolbox backend which has ridiculous low-latency performance! Published data on the [timing megastudy here](https://peerj.com/articles/9414/)

**Closed by peircej** 2020-08-04 16:40 UTC
