### ISSUE TITLE
The new interface icons are still not retina-compliant

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#2899] opened 2020-06-22 04:00 UTC
A lot of work has gone in to improving the consistency of the interface but unfortunately on a Mac using a retina-scale display:
- the new icons still appear at low resolution in the component panel,
- all icons ~~and text labels~~ in the timeline panel are low-resolution,
- ~~the boxes, their names, and durations in the flow panel are also low resolution.~~

***Edited 2020-09-08 as at release 2020.2.4***  to reflect that there is now retina-level rendering of elements other than component icons.

All of these things were true before, but with the upgraded and simplified icons, the issue has actually become more apparent than it was before.  

~~A few~~ Most text labels (e.g. the names of the component categories in the component panel ~~and the "Insert routine" and "Insert loop" text labels in the flow panel~~) do render in high resolution, and this heightens their distinction against the adjoining ~~low resolution text and~~ icons.

**Comment by mdcutone** [comment] 2020-06-22 18:19
I think `GetContentScaleFactor` can be used to detect the application is running on a retina display. This can also help with the text scaling within builder's routine view when being viewed on a high DPI display.

**Comment by peircej** [comment] 2020-06-23 08:42
One good thing is that, now that @TEParsons has created the icons himself in vector formats we can generate any resolution. The issue is explaining to wx/macOS that it should use a 96x96 image as a 48x48 button.
There are some thoughts on that here: https://groups.google.com/forum/#!topic/wx-users/GEWSNxvhv30
It might be that simply calling an image myIcon48@2X, and making it actually a 96 pixel icon, will work but otherwise we might need to hack the scaling parameter during load

**Comment by peircej** [comment] 2020-06-23 09:18
And to detect that the scaled versoin is needed we can check `wx.Frame.GetContentScaleFactor()` which I've just checked on my retina mac does return 2.0

**Comment by peircej** [comment] 2020-07-03 09:19
https://discuss.wxpython.org/t/hidpi-scaling-and-4-0-7/34264/7
https://discuss.wxpython.org/t/help-with-high-dpi-icons/34544

**Comment by peircej** [comment] 2020-07-15 16:02
Actually this one isn't done. It just probably won't be done any more in the current release. I'll remove it from the Milestone but leave it as an outstanding issue

**Comment by cbrnr** [comment] 2020-12-11 10:56
I just tried the latest release (2020.2.10) on my Mac and it seems like this hasn't been fixed. I had a similar issue with MNELAB (https://github.com/cbrnr/mnelab/pull/102/files), which is based on PyQt5. I had to do `app.setAttribute(Qt.AA_UseHighDpiPixmaps)` to enable proper hi-res rendering of icons (even though the icons were already high-res or even SVGs). Maybe there's a similar setting in wxPython?

**Comment by peircej** [comment] 2020-12-11 13:23
I've spent a fair amount of time trying to make it work and I've got about as far as I can. I actually think most of the icons now look fine (e.g. in the Components panel) but tabs labels (e.g. for the Routines) are certainly ugly. I think short of us moving to another system, or wx simply improving, this is about as good as it gets.

I'm actually going to close this now on the basis that I'm not planning to work on it further, although happy to receive pull requests from people if they find additional fixes of course.

**Closed by peircej** 2020-12-11 13:23 UTC

**Comment by cbrnr** [comment] 2020-12-11 14:52
SVG support should already work: https://discuss.wxpython.org/t/scalable-icons/33015/13 - did you try that? Do you have SVG icons? Then I'd go that route instead of manually resizing/selecting suitable bitmaps.

**Comment by cbrnr** [comment] 2020-12-11 19:08
Exactly - but the conversion from SVG to bitmap should be handled by wx to yield high resolution icons on retina displays. That's also what Qt does, but you have to set this property, otherwise the created bitmap is low res.

**Comment by peircej** [comment] 2020-12-12 12:19
I understand all that. I've spent a fair bit of time on this and haven't managed to get further. When I've tried using scaled images from wx it has not scaled correctly, but if you succeed where I've failed that's great!
