### ISSUE TITLE
Ability to rename routines

### ISSUE THREAD

**Issue by wildetudor** [psychopy/psychopy#1120] opened 2016-02-22 12:52 UTC
Just a +1 to the older suggestion about adding an ability to rename not only components but also the routines that contain them. Right now there is only a Remove command for the right-clcik menu of routines. The current suggested workaround of doing a Find&Replace in the editor view is not only cumbersome but also does not seem to work, due to the unclarity about how manually edited code can be turned back into Builder (it probably can't).
Cheers!

**Comment by jeremygray** [comment] 2016-02-23 12:00
The find & replace suggestion should work for the .xml in a .psyexp script, and remain in a Builder-compatible format. (Find whole words, match case.) You are right that it would work in generated code, but not be able to be turned back into Builder format (definitely can't).

**Comment by peircej** [comment] 2016-02-23 18:19
I agree though that it should be available in Builder

**Comment by peircej** [comment] 2016-02-23 18:24
But this is a duplicate of #142

**Closed** 2016-02-23 18:24 UTC
