### ISSUE TITLE
pytest_namespace not available in latest pytest

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2189] opened 2019-01-09 13:30 UTC
`pytest` 4.1.0 [removed](https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace) the previously-deprecated `pytest_namespace`, which means our tests won't run with the newest `pytest` versions as `tests/conftest.py` [makes use of the removed feature](https://github.com/psychopy/psychopy/blob/b75b813eb8b18ccf6083cfdb1426bdf9f12e9226/psychopy/tests/conftest.py#L8).

[More info on `conftest.py`](https://docs.pytest.org/en/latest/writing_plugins.html#conftest-py-local-per-directory-plugins)

Interim solution: pin `pytest` version to `<4.1.0`.

**Comment by peircej** [comment] 2019-01-10 16:43
Yes, let's fix to <4.1.0 for now

**Comment by hoechenberger** [comment] 2020-01-11 11:48
Just wanted to bump this one back into awareness :)

**Comment by peircej** [comment] 2020-01-12 13:20
Filling me with dread! ;-)

**Comment by danielshub** [comment] 2020-04-22 17:47
I am using the pandemic as a chance to update my experiments to a newer version. Is pytest still pinned at <4.1?

**Comment by peircej** [comment] 2020-04-22 19:08
I'm afraid so - I spent several days trying to update the test suite to the new mechanisms and couldn't get it to work - from my memory the issue is that the app starts up but then doesn't exit cleanly

**Comment by peircej** [comment] 2021-08-17 15:23
This is definitely fixed now. It was a world of pain but we are now using the pytest fixtures of >4.1

**Closed by peircej** 2021-08-17 15:23 UTC
Labels: 🧪 tests
