### ISSUE TITLE
useVersion causing errors in older experiments

### ISSUE THREAD

**Issue by jvcasillas** [psychopy/psychopy#1515] opened 2017-09-16 16:38 UTC
I posted about this issue [here](https://discourse.psychopy.org/t/useversion-error-in-1-85-3/3065) on the psychopy forum, but I've yet to get a response so I wanted to try my luck here. 

**OS**: Mac OS X
**PsychoPy version**: 1.85.3
**Standard Standalone**?: yes
**What are you trying to achieve**?: I am trying to run my experiment in builder. I get the following error:

    psychopy.useVersion('latest')
    AttributeError: 'module' object has no attribute 'useVersion'

**What did you try to make it work**?: Under the Experiment Settings window I have tried changing the “Use PsychoPy Version” setting.

**What specifically went wrong when you tried that**?: I get the same error. Also, after making any changes to the experiment, I am unable to save. I click on the save icon and nothing happens (i.e. it doesn’t fade as it normally does when the experiment has been saved).

The experiment was working fine about a month ago and I do not recall making any changes. If I compile to coder and remove the following line: 

    psychopy.useVersion('latest')

...everything works as it should. Any ideas?

**Comment by CRiddler** [comment] 2017-09-16 19:01
This issue should've been fixed about a week ago. #1507 does this need to be backported to other psychopy versions? @peircej

Aside from fixing it on our end, an easy fix for you should be to set the "Use PsychoPy Version" setting under Experiment Settings to the blank one. Let me know if this suggestion doesn't fix it though!

**Comment by jvcasillas** [comment] 2017-09-16 23:57
Hello @CRiddler. Changing "Use PsychoPy Version" setting does indeed allow me to run the experiment (thank you); however, I am still unable to save the change. Clicking on the icon does nothing and when I try "save as" a new .psyexp file is not generated.

**Comment by jvcasillas** [comment] 2017-09-17 14:37
Update: I figured out a workaround. I downgraded to version 1.85.2 and saved my experiment with "Use PsychoPy Version" set to blank. Then I upgraded to 1.85.3 and I can run the experiment. However, if I make any changes at all (even just selecting a component and then pressing "OK" without making any changes) I am no longer able to save. Clicking the save icon simple does nothing. I assume this is a bug, right?

**Comment by CRiddler** [comment] 2017-09-17 16:29
This definitely sounds like a bug to me. Can you try making a brand new experiment and saving that? I just want to see if the saving issue is unique to the experiment you've been working. I'll take a look into psychopy's code tomorrow to see if I can weed the problem out.

**Comment by jvcasillas** [comment] 2017-09-17 17:41
I can create a new experiment under 1.85.3 and save it without problems. The issue seems to be creating an experiment under 1.85.2 and then editing it in 1.85.3.

**Comment by CRiddler** [comment] 2017-09-17 18:36
Ah great. That gives me some info on where I should start to look. Are you doing all the editing and saving in the builder mode?

**Comment by jvcasillas** [comment] 2017-09-17 19:26
Yes, everything in builder. I started to play in coder in order to figure out a workaround because I am able to save there. Let me know if I can help by giving you more info (or in any other way).

**Comment by peircej** [comment] 2017-09-18 09:58
Hi @jvcasillas and thanks for persisting with this. So, the `useVersion()` issue itself has gone but saving has become a problem. Could you see if an error message is being hidden:

-  open coder view (with output in bottom panel)
-  in Builder view make your change and try to save
- did an error appear in the output panel?

I'm puzzled though because if you're using the 1.83.5 release then you shouldn't be seeing this problem. Is it possible that someone has installed a development version from the github repository rather than a version from the "releases" page?
https://github.com/psychopy/psychopy/blob/1.85.3/psychopy/__init__.py
So, no, we *shouldn't* need to port this to any other branch - I don't *think* the bug was ever in a released version. :-/

**Comment by jvcasillas** [comment] 2017-09-18 12:17
I just gave it a try and there was no error. Nothing happens at all. Just to clarify, I am using 1.85.3 (not 1.83.5). I've never used any version from the GitHub repository. [Here](https://www.dropbox.com/s/4rfla9jj3adsfja/2afc.zip?dl=0) is a link to the experiment if you would like to take a look. I am interested in knowing if the issue is reproducible. Again, the experiment was built under 1.85.2 and changes cannot be saved under 1.85.3.

**Comment by CRiddler** [comment] 2017-09-18 18:17
@jvcasillas where did you download psychopy 1.85.3 from? Was it the main website psychopy.org?

@peircej if this is from the main website, I encountered the same `useVersions()` which is why I knew of the workaround of setting it to blank. I can't find the standalone 1.85.3 on psychopy.org for some reason (it says 1.85.2 is the latest, but that's definitely where I downloaded it about 1 month ago). Perhaps there's a mismatch between the github 1.85.3 and what got put into the standalone version on the site? Not exactly sure what all goes into creating the standalone versions, but this could be a potential reason.

@jvcasillas I'm looking into the save issue now, it may take a little while though since we don't have any log of where to look specifically, but I'll comment here if I find anything.

**Comment by jvcasillas** [comment] 2017-09-18 18:36
@CRiddler I am almost certain it was from psychopy.org (I got the update message when I opened 1.85.2 and updated accordingly).

**Comment by CRiddler** [comment] 2017-09-18 20:31
@peircej I've tracked down the error. Unfortunately it has to do with the py2 --> 3 support switch that has been made. The reason @jvcasillas can't save in 1.85.3 is because he has non-ascii text stim. The reason that this is an issue in the builder and not the coder is because the builder save method saves it to an xml file, and inside the xml save we're calling `"{}".format(param.val)` inside `thisChild.set('val', "{}".format(param.val).replace("\n", "&#10;"))`

The reason this works in psychopy 1.85.2 is because instead of `"{}".format(param.val)` we used `unicode(param.val)` Unfortunately since the goal is to be py2/3 compatible we need a workaround that can set thisChild.val to unicode in python2, but string in python3. 

My initial thought is the check for python2 and if it is python2, check the object is unicode, then do `thisChild.set('val', param.val.replace("\n", "&#10;"))` and skip the `.format()` call because our object is unicode. Overall my suggestion looks like this: 

lines 345-349 in `psychopy/app/builder/experiment.py` (sorry I'm not sure if theres a way to manually link the lines in said file to this comment)

        if hasattr(param, 'val'):
            if not PY3 and isinstance(param.val, unicode):
                thisChild.set('val', param.val.replace("\n", "&#10;"))
            else:
                thisChild.set('val', "{}".format(param.val).replace("\n", "&#10;"))

I've tested this saving and reloading the experiment and it maintains unicode characters properly for python2. I haven't tested on python3 though (currently don't have a psychopy set up with py3). I'd like more heads looking at this so I'll tag @hoechenberger to take a look and see what he has to say.

@jvcasillas I'd suggest you stick to 1.85.2 for now, as this issue is inherent to python and not psychopy so there might be a few ideas bumping around on how to properly handle this. Unless there's some features that you need in 1.85.3- then my next easiest suggestion is to get rid of the following:
* the upside-down question mark in `check_text`
* the non ascii apostrophe in `rest_text`
* The "A" with an accent in `trial_status_text`

And by removing all 3 of those, you should be able to save in 1.85.3, but honestly- just stick with 1.85.2 for now unless theres really something you need in it.

Now if you REALLY want 1.85.3 and want to keep your non-ascii text, then you need to try to implement my current workaround that I mentioned above in this comment (you'd essentially be adding 2 lines of code to `psychopy/app/builder/experiment.py`)

**Comment by jvcasillas** [comment] 2017-09-18 20:34
Excellent! Thank you.

**Comment by CRiddler** [comment] 2017-09-18 20:35
Yep! Let me know if you have other questions, I'm sure we'll have a patch for this within the next couple of days.

**Comment by peircej** [comment] 2017-09-19 20:05
OK, I can confirm that some of the wrong files were included in the 1.85.3 release (that should have been kept back for the 1.86 release). So the unicode issue you bring up is something that we'll need to fix in 1.86 but shouldn't have been included in this bug-fix release.

Apologies for the hassle this has caused!

**Comment by CRiddler** [comment] 2017-09-19 20:09
Ah that's good to know. At least we found something substantial to fix for the 1.86 release out of all this! :)

**Comment by peircej** [comment] 2017-09-19 20:15
I suspect we need to fix lots of new unicode bugs in the 1.86 version (both in the python 2.7 and the 3.6) because of many ways that side of the code has changed.

**Comment by CRiddler** [comment] 2017-09-20 16:56
With a suggested fix in place and the overarching issue that arose from 1.86 leaking into the standalone, should we close this since you fixed the standalone version issue in #1518?

**Comment by peircej** [comment] 2017-09-20 17:44
Probably yes, we should close this. Certainly the bug in the original post is fixed in the master branch.
The potential issue is still the `"{}".format(param.val)` part that you found. I was surprised that was a problem because I was hoping this was a good solution in both versions. If you're right about it then this might well crop up again in 1.86 (which currently uses that syntax in several places).

**Closed by peircej** 2017-09-20 17:44 UTC

**Comment by hoechenberger** [comment] 2017-09-20 18:20
@CRiddler Great detective work!
