### ISSUE TITLE
Wrong mouse location returned by myMouse.getPos()

### ISSUE THREAD

**Issue by oliver-xie** [psychopy/psychopy#4684] opened 2022-03-10 22:13 UTC
Version: Psychopy v2022.1 
MacOS Retina screen 
The mouse location returned by myMouse.getPos() is off by half of the screen size in the mouse.py demo.

**Comment by TEParsons** [comment] 2022-03-11 12:37
We're working on this bug and should have a fix in by 2022.1.2, it's to do with how retina displays represent pixels. The bug is specific to the `glfw` window backend so if you change "Window Type" in Preferences to be either `Pyglet` or `PyGame` it gets around the problem until we have a more permanent solution

**Comment by thoklei** [comment] 2022-04-05 15:17
Hi, are there any news on this? I'm on 2022.1, on macOS. Running the mouse.py demo also does not work properly for me, same problem as @oliver-xie. But I also have this issue in an actual application, where the offset mouse position makes it impossible to use a slider (because the location of the mouseclick does not match the position at which the slider is rendered). Changing the winType-argument of visual.Window() to pyglet does not fix this.

**Comment by mdcutone** [comment] 2022-04-05 19:14
Hello @thoklei, I'm working through this issue this week. The issue is around inconsistent scaling of window coordinates on retina displays.

**Comment by TEParsons** [comment] 2022-04-08 11:03
Fixed in #4755

**Closed as completed by TEParsons** 2022-04-08 11:03 UTC
Labels: 🐞 bug, 🔧 hardware/iohub
