### ISSUE TITLE
coder file save dialog can be pesky

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#755] opened 2014-12-05 17:04 UTC
When saving a file to a name that already exists, I typically get 2 (sometimes 3) prompts to check whether I really want to replace the file. "untitled.py" seems to be especially prone to this.

**Comment by hoechenberger** [comment] 2016-10-14 20:12
Cannot reproduce in latest release, closing.

**Closed by hoechenberger** 2016-10-14 20:12 UTC
