### ISSUE TITLE
Corrupted GratingStim when changing sf before size (but not the other way around)

### ISSUE THREAD

**Issue by smathot** [psychopy/psychopy#1318] opened 2016-12-09 15:12 UTC
When I run this (in OpenSesame, so `win` is `psychopy.visual.Window`):

~~~ python
import numpy as np
from psychopy.visual import GratingStim

s = GratingStim(win, tex=np.random.random([4,4]))
s.sf = None
s.size = 400, 400
s.draw()
win.flip()
~~~

I see the following corrupted image:

![image](https://cloud.githubusercontent.com/assets/594936/21053476/da9f6514-be29-11e6-8163-a25a967d5019.png)

If I switch the order in which `s.size` and `s.sf` are set, things work fine:

~~~ python
import numpy as np
from psychopy.visual import GratingStim

s = GratingStim(win, tex=np.random.random([4,4]))
s.size = 400, 400
s.sf = None
s.draw()
win.flip()
~~~

![image](https://cloud.githubusercontent.com/assets/594936/21053502/fea1fe04-be29-11e6-9598-22a397ca7627.png)

System info:

![image](https://cloud.githubusercontent.com/assets/594936/21053533/2350e2ba-be2a-11e6-91a4-0cae06fa2572.png)

**Comment by hoechenberger** [comment] 2016-12-15 12:23
I could replicate this with 1.84.2 on Windows.

**Comment by peircej** [comment] 2016-12-15 15:30
I *think* the issue here is the handling of a default argument. SF, in reality, has to be *something*. Usually, if we're given a size, and the user sets SF to None then can set SF to be 1.0/size so that there is exactly one cycle. In your case you've got `size=None` as well as `sf=None` and PsychoPy hasn't got a rule to handle so few constraints. We can add a rule to handle such a thing but right now I think it isn't being handled.

**Comment by peircej** [comment] 2016-12-15 15:32
Yes, as further evidence, if I set sf to an actual value then it doesn't matter whether I set it before or after the size. The issue is setting it to `None` before a size has been set.

**Comment by smathot** [comment] 2016-12-16 08:17
Yes, I was thinking along those lines as well. The problem doesn't occur often, but there's at least one real-life situation in which it happens (it's how I found out): If you want to dynamically change both the frequency and the size, and by chance choose the 'wrong' order.

**Comment by TEParsons** [comment] 2022-03-14 14:54
This seems to be fixed now - I think because default size is handled by `layout` so it's able to return a default value without being manually set. Running the first code snippet in 2022.1.1 in Windows 10 gives the correct image.

**Closed by TEParsons** 2022-03-14 14:54 UTC
Labels: 🐞 bug, 👀 visual
