### ISSUE TITLE
color attribute of visual.Rect doesn't work

### ISSUE THREAD

**Issue by tmalsburg** [psychopy/psychopy#931] opened 2015-06-26 01:42 UTC
According to the [documentation](http://www.psychopy.org/api/visual/rect.html#psychopy.visual.Rect), `visual.Rect` has a color attribute.  However, when I specify it in the constructor, I get an

    TypeError: __init__() got an unexpected keyword argument 'color'

and when I set it after construction

    rec = visual.Rect(win, x2-x1, y2-y1, lineColor=(1,0,0), fillColor=(0,1,0))
    rec.color = (0,0,1)

it doesn't have any effect.

Given that there already is `lineColor` and `fillColor', `color` is actually redundant.  Is this a bug in the documentation? 

Btw, passing a `colorSpace` parameter to the constructor also generated an unexpected keywords error.

**Comment by tinyrobots** [comment] 2015-07-09 12:00
Same behaviour for visual.Circle

**Comment by peircej** [comment] 2015-07-09 15:00
duplicate of #908

**Closed by peircej** 2015-07-09 15:00 UTC
