### ISSUE TITLE
 WARNING: sounddevice audio lib was requested but not loaded: sounddevice not working

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2284] opened 2019-02-17 16:29 UTC
Dear all,
I recently downloaded the latest version (standalone version) of PsychoPy on Mac (Book Pro, 2018), and when I open PsychoPy3 Coder, I got this message:
`5.6644     WARNING     sounddevice audio lib was requested but not loaded: sounddevice not working`, could you please tell me how I can load the necessary sounddevice?
Many thanks in advance

**Comment by peircej** [comment] 2019-02-18 10:01
By latest version you mean 3.0.3? And this was the Standalone package? I'm not sure why that would not have worked. Could you go to the Coder window and:

- load/run the demo/stimuli/soundStimuli.py (or whatever it's called). Could you paste all of its output here?
- go to the shell panel at the bottom of the window and type `import sounddevice, soundfile` and again paste any output here

thanks

**Comment by SanRut** [comment] 2019-02-18 10:59
Hello, I'm having the same issue. I'm running version 3.0.3 and I'm using OS 10.14. 

Here is the output when running the soudStimuli.py:
##### Running: /Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/demos/coder/stimuli/soundStimuli.py #####
1.2573     WARNING     sounddevice audio lib was requested but not loaded: sounddevice not working
Traceback (most recent call last):
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/demos/coder/stimuli/soundStimuli.py", line 22, in <module>
    from psychopy import sound, core
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/sound/__init__.py", line 107, in <module>
    .format(prefs.hardware['audioLib']))
psychopy.exceptions.DependencyError: No sound libs could be loaded. Tried: ['sounddevice']
Check whether the necessary sound libs are installed

And here is the output from the shell:
import sounddevice
soundfile
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'soundfile' is not defined

Thanks a lot!

ps: the pygame library does work. The pyo library runs, but gives very disturbing sounds and the experiment does not finish properly. But this is a known issue if I'm correct right?

**Comment by SanRut** [comment] 2019-02-18 11:01
ps: it is the standalone package

**Comment by peircej** [comment] 2019-02-18 11:08
Thanks. That looks like importing sounddevice itself didn't raise any issues. In the shell could you do `import soundfile` (last time you put that on a different line which gave the error)

**Comment by SanRut** [comment] 2019-02-18 11:17
import soundfile indeed does not raise an issue.

**Comment by SanRut** [comment] 2019-02-18 11:20
import soundfile does not give an error.

**Comment by peircej** [comment] 2019-02-18 12:01
Ah, I think I might know what this is about. I'm building a new version for you to try.

**Comment by SanRut** [comment] 2019-02-18 12:10
Ok, thanks a lot!

**Comment by peircej** [comment] 2019-02-18 12:57
Could you try installing this one?

https://github.com/psychopy/psychopy/releases/download/3.0.4/StandalonePsychoPy3-3.0.4b-MacOS.dmg

**Comment by SanRut** [comment] 2019-02-18 13:08
Thanks for this! It is running now, but it does not play the sounds correctly. It is giving these disturbing sounds as it does when using the pyo library (with the 3.0.3 version).

**Comment by mmolet** [comment] 2019-02-18 13:28
Thank you very much Jon for making a new Standalone package, there is no more problem on my end!

**Comment by minnie2112** [comment] 2019-03-06 12:24
Dear all, 
I am using the 3.0.4 Standalone version of Psychopy on Windows10. 
I have the same warning message (see below)
![warning](https://user-images.githubusercontent.com/48283084/53881053-f2e20b00-4012-11e9-9f92-08d8e908ba5e.png)
The 3.0.5 version of Psychopy had problems with creating a pyo server that is why I have downloaded the 3.0.4 version. 

I would appreciate any kind of help.

**Comment by Arinelle** [comment] 2019-03-26 10:01
I have the same problem on Windows. I installed PsychoPy with pip, so I have v3.0.4.
I tried to install pyo as well, but it is not recognized. Here is my output log:
"v3.0.4
7.5589     WARNING     Monitor specification not found. Creating a temporary one...
8.2771     WARNING     sounddevice audio lib was requested but not loaded: sounddevice not working
8.2809     WARNING     pyo audio lib was requested but not loaded: ModuleNotFoundError("No module named 'pyo'")"
import soundfile worked in the shell.
Thank you for your help.

**Comment by peircej** [comment] 2019-03-26 10:03
Sadly, pyo doesn't support pip yet, so has to be installed by its double-click installers:

http://ajaxsoundstudio.com/software/pyo/

**Comment by Arinelle** [comment] 2019-03-26 10:04
Yes, so that's what I did. I installed the Windows, python 3.6, 32-bit version.

**Comment by peircej** [comment] 2019-03-26 10:07
My guess is that you have mulitple Python installations and you've only installed pyo to one of them. Maybe use the PsychoPyStandalone so that you have all the compatible dependencies in one known place?

**Comment by Arinelle** [comment] 2019-03-26 10:15
I have only one install, however, it's a local one (C:\Users\myUserName\AppData\Local\Programs\Python\Python37-32).
Pyo, however, is installed globally. I left the default install path: C:\Python36-32.
I guess that's the issue then, any idea how to solve it? Local install pyo?

**Comment by Arinelle** [comment] 2019-03-26 17:04
I reinstalled pyo in the local folder. No change to the error message.

**Comment by peircej** [comment] 2019-03-26 17:39
Well, it looks frmo the paths you've specified above, like you've got Python3.7 and you're trying to install pyo for Python3.6 (there isn't a version yet for Py3.7 which means you'd have to compiled your own.

Is there a reason you can't install Standalone PsychoPy. The reason we provide that is to solve exactly these sorts of issues.

**Comment by peircej** [comment] 2019-03-26 17:41
For the original topic of this issue (non-existent sounddevice lib) I believe the problem is solved so I'm closing.

**Closed by peircej** 2019-03-26 17:41 UTC
