### ISSUE TITLE
Issues with PsychoPy 1.90.1 (Python 2 edition - Windows 10)

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#1821] opened 2018-05-10 10:19 UTC
Hi there,

We recently tested out 1.90.1 (Python 2 edition) with a number of our scripts, and found a number of issues.  

This was using a Dell Optiplex 7050 (http://www.dell.com/en-uk/work/shop/desktop-and-all-in-one-pcs/optiplex-7050-tower-small-form-factor/spd/optiplex-7050-desktop) with Windows 10 installation.

Here are the issues spotted:

- [x] **1)** Hex colour encoding not working correctly.   Seems to create a speckled effect when used for a background colour.   My colleague has reported also at https://discourse.psychopy.org/t/hexadecimal-color-strings-not-working/4471

- [x] **2)** There is a "Unknown stereo type -1" error when using Sound class in Coder and using the "Sounddevice" codebase.   Workaround is to have to set "stereo=True" on a sound() call, though documentation doesn't seem to mention that you have to include this.

- [x] **3)** On the initial run, PsychoPy tries to download ffmpeg.  This fails.   When manually trying to kick off again, you see an error reporting why:
`"Error while fetching file: <urlopen error [SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c.590)>"` Internet connection is confirmed as fine, and the same issue occured on another test machine.

- [x] **4)** When using a sound component, when pulling duration from an Excel file,  it causes the following error: `"Could not convert string to float: VARIABLE NAME"` Seems like the autoconversion from Excel is broken, specficially at \psychopy\experiments\components\sound\__init__.py line 65 in writeInitCode.

- [ ] **5)** If playing audio files with different encodings,  it fails when using "sounddevice" with a `"psychopy.exceptions.SoundFormatError: Tried to create audio stream 48000_1_128 but 44100_1_128 already exists and win32 doesn't support multiple portaudio streams"` error

- [x] **6)** PYO sound was broken on the Dell Optiplex 7050 (at least).   Segmentation fault on desktop PC,  "Server must be booted" error. A sound driver update initially worked, but then the issue would still occur on other scripts - due to initialization of the portaudio server I think?

- [x] **7)** Moviestim2 demo does not work.  Complains about VLC module not being present, even though VLC has been installed/reinstalled.  This actually affects using OpenCV though as a movie playback type.

- [ ] **8)** Moviepy playback option works and plays an Mp4 video once, slightly out of sync - doesn't allow playback of a second video and crashes out without any kind of error message when it tries to.

Let me know if you need any more details.

Best wishes,

Frank

**Comment by hsogo** [comment] 2018-06-13 11:19
### Issue 7)
I confirmed that `vlc` module is not properly installed in Standalone PsychoPy 1.90.1 and 1.90.2 for Windows.

In these versions, vlc.py is in psychopy/visual directory.  This module was  importable from psychopy/visual/movie2.py in the previous version of PsychoPy, but it cannot be imported in the current version due to use of `absolute_import`.

In python3 version of Standalone PsychoPy 1.90.1 for Windows, `vlc` module is properly installed.

In addition to installation of `vlc` module problem, version of VLC media player may cause trouble.  Because Standalone PsychoPy for Windows uses 32bit python, 32bit version of VLC media player must be installed.

**Comment by peircej** [comment] 2018-06-19 09:43
I think:

3. is due to an old version of Python2.7 being in the last release. I've updated to Python 2.7.15 for the next release which I believe contains newer SSL certificates
5. I think this is a "won't fix". Users need to get all their sounds into the same sample rate. On Windows portaudio doesn't allow multiple sound streams with different rates, so to allow different sampling rates would require us to resample the sounds while playing them, which would be less efficient.
7. I've confirmed that the vlc lib is installed and working for both py2 and py3. The issue of requiring 32bit vlc seems necessary unless we can provide 64/32bit options of Python (I don't know if it's worth the confusion of adding another release type)

Not sure what to do about (6). And (8) still needs exploring

**Comment by dvbridges** [comment] 2018-06-19 09:53
I was just looking at solutions to 5) and was going to suggest an option to resample using [samplerate](http://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html) which is a wrapper around the [Secret Rabbit Code - a lib for high-quality sample rate conversion](http://www.mega-nerd.com/SRC/win32.html).

**Comment by liffiton** [comment] 2018-07-09 21:05
I ran into the same issue with how movie2 imports vlc in 1.90.3.  My script, using movie2, would crash with the error:

```
ImportError: No module named vlc
```

A quick fix was to change [move2.py:110](https://github.com/psychopy/psychopy/blob/ede5eaf46e49a8ad67c24df8d3398465d47b5165/psychopy/visual/movie2.py#L110) to `from psychopy.visual import vlc`.  That fixed it for me.

**Comment by liffiton** [comment] 2018-07-16 18:17
Sorry, I should also point out that this was with 32-bit PsychoPy 1.90.3 under Windows.

**Comment by TEParsons** [comment] 2021-08-05 09:13
Given the stuff @mdcutone has been doing recently I'd wager 5 is no longer relevant as audio is totally different behind the scenes now, and movie stim is next up for these changes so 8 may well be fixed soon too. Matthew can you confirm?

**Comment by mdcutone** [comment] 2021-08-20 14:22
Many of these issues were resolved by the inclusion of the PTB audio backend. Movie playback improvements are ongoing but vastly improved at this point.

**Closed by mdcutone** 2021-08-20 14:22 UTC
Labels: 💻 app/ui, 🐞 bug, ⏰ waiting for feedback
