### ISSUE TITLE
Grainy rendering of solid window colour

### ISSUE THREAD

**Issue by nat-n** [psychopy/psychopy#445] opened 2013-11-23 17:25 UTC
I'm running a relatively new clean install of OSX Mavericks, with Xquartz 2.7.5 (2013-11-10 release), on a 2012 macbook pro, PsychoPy 1.7.8.01.

I execute the following code from the Coder:

    import time
    from psychopy import visual

    win = visual.Window(monitor='testMonitor',  fullscr=True, rgb=[0.3,0.3,0.3])
    stm=visual.PatchStim(win=win)
    stm.draw()
    time.sleep(10)

The issue is that the grey background has a grainy texture even though a solid colour is specified.
 [As per this section of a screenshot](https://f.cloud.github.com/assets/880829/1606929/1c763734-5464-11e3-97b4-2ae95045112c.png)

Anyone seen this before?

**Comment by hoechenberger** [comment] 2016-10-14 20:37
Cannot reproduce with latest release on macOS Sierra, closing.

**Closed by hoechenberger** 2016-10-14 20:37 UTC
Labels: bug, library, platform mac
