### ISSUE TITLE
Could not find Cedrus device

### ISSUE THREAD

**Issue by eyexciteme** [psychopy/psychopy#2763] opened 2020-01-15 22:34 UTC
Attempting to use the Cedrus response box in multiple routines in my experiment. It works fine when used in a single routine, but when I try to use it in more than one routine (e.g., to have a practice block and then experimental block) PyschoPy returns the error "Could not find Cedrus device". This is apparently is an open issue. 

Apparently PsychoPy doesn't know how to reuse an object that was already created. 

Please consider addressing.  

Thank you!

**Comment by peircej** [comment] 2020-01-16 10:53
Yes, we're aware of this one, but good to list here. 

The problem is that the button box can't be initialised twice (whereas PsychoPy initialises it for each instance of the component). The workaround is that you insert the each-frame code yourself for the button box, for now I'm afraid.

**Comment by peircej** [comment] 2020-02-07 14:42
This is fixed in release 2020.1

**Closed by peircej** 2020-02-07 14:42 UTC
Labels: bug, effort medium
