### ISSUE TITLE
psychopy components can't open [Bug]: 

### ISSUE THREAD

**Issue by swg168** [psychopy/psychopy#6344] opened 2024-03-31 10:03 UTC
### PsychoPy Version

2024.1.0

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

`Traceback (most recent call last):
  File "D:\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3319, in onPluginBtn
    dlg = psychopy.app.plugin_manager.dialog.EnvironmentManagerDlg(self)
  File "D:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\dialog.py", line 43, in __init__
    self.pluginMgr = PluginManagerPanel(self.notebook, dlg=self)
  File "D:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 258, in __init__
    self.pluginList = PluginBrowserList(self.splitter, stream=dlg.output)
  File "D:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 488, in __init__
    self.populate()
  File "D:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 496, in populate
    items = getAllPluginDetails()
  File "D:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 1270, in getAllPluginDetails
    localPluginDatabase = json.loads(localPluginDatabase)
  File "D:\PsychoPy\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\PsychoPy\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\PsychoPy\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

### Expected Behaviour

I want to download the tobii eyetracker plugin and test it, but can't open the component page
![image](https://github.com/psychopy/psychopy/assets/109449633/12ab80a3-7fed-48fe-b533-18603933d9af)

### Steps to Reproduce

1. installed the StandalonePsychoPy-2024.1.0-win64.exe 
2. open psychopy and click the "Get more" in the components
3. can't open and report bug
...

**Comment by peircej** [comment] 2024-04-02 11:18
@TEParsons has [a fix to be pulled in](https://github.com/psychopy/psychopy/pull/6334) for this (will be in 24.1.1) but in the meantime you should be able to fix it manually by deleting the file
`%AppData%/psychopy3/cache/plugins.json`

The bug is caused by PsychoPy not having internet access at some point while launching (we think) and then failing to update its cached list of available plugins when the internet became available

**Comment by swg168** [comment] 2024-04-02 11:57
According to your instructions, I deleted the %AppData%/psychopy3/cache/plugins.json file. Although I successfully accessed the plugin page afterwards, I couldn't load the plugin list even after waiting for 5 minutes. I also tried using a proxy, but the problem persisted. I guess I'll have to wait for the next version.

**Comment by peircej** [comment] 2024-04-02 14:57
The original issue was something we've seen before, but this sounds new. Could you confirm what the view looks like when you wait? The file is a very small JSON so this shouldn't take time to download

**Comment by swg168** [comment] 2024-04-03 05:15
sure, the first screenshot is the plugin list page, you can see it is blank.  And the time is 13:00

![20240403_130006_854_copy](https://github.com/psychopy/psychopy/assets/109449633/70f3384c-e290-42d8-862a-0b46e41726a1)

 after I waited for 3 min, the page was still blank, you can see that in the second screenshot.
![20240403_130324_374_copy](https://github.com/psychopy/psychopy/assets/109449633/a20fbf57-b32e-43b6-9177-6fc2c8593b24)

I think the problem is even though I successfully accessed the plugin list page, the file was not downloaded.  I checked the folder %AppData%/psychopy3/cache,  and not founded the plugins.json file.

**Comment by peircej** [comment] 2024-04-03 09:29
In that screenshot it looks like you've typed something into the search window in Chinese characters but the packages don't contain any Chinese characters in their name, so nothing is showing. Remove those characters and you should see this:
<img width="416" alt="image" src="https://github.com/psychopy/psychopy/assets/380582/ff7997f5-2b65-4046-984a-d3eec8647d0b">

**Comment by swg168** [comment] 2024-04-03 11:24
The Chinese character is the implicit instruction of the search symbol. It's not what I typed.
Even if I change the language of Photoshop to English, this still exists, and it only disappears when I double-click to try typing.
![image](https://github.com/psychopy/psychopy/assets/109449633/59136416-e8f7-4cc6-a014-7d69d3046015)

**Comment by peircej** [comment] 2024-04-03 11:27
Well that's even more weird. Could I also just confirm that this computer is connected to the web? You can go to psychopy.org from a browser, for instance?

**Comment by swg168** [comment] 2024-04-03 11:33
我的电脑连接了网络，可以正常访问 psychopy.org 
![20240403_192931_269_copy](https://github.com/psychopy/psychopy/assets/109449633/78b85696-64ff-49fb-8390-c86d55d873af)

事实上，我不确定是否是我的网络导致该问题，只有我使用网络代理时，我才能进入plugin list page, 如果我使用中国的ip，将会返回下面的bug。
`Traceback (most recent call last):
  File "E:\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3319, in onPluginBtn
    dlg = psychopy.app.plugin_manager.dialog.EnvironmentManagerDlg(self)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\dialog.py", line 43, in __init__
    self.pluginMgr = PluginManagerPanel(self.notebook, dlg=self)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 258, in __init__
    self.pluginList = PluginBrowserList(self.splitter, stream=dlg.output)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 488, in __init__
    self.populate()
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 496, in populate
    items = getAllPluginDetails()
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 1249, in getAllPluginDetails
    f.write(serverPluginDatabase)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 8878: illegal multibyte sequence
`

**Comment by swg168** [comment] 2024-04-03 11:37
My computer is connected to the network and can access psychopy.org normally。 I am not sure if my Chinese IP is causing this issue, as when I use my Chinese IP to access the plugin list page, I will return the following bug. Only when I use a network proxy can I successfully access the plugin list page. 
`Traceback (most recent call last):
  File "E:\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3319, in onPluginBtn
    dlg = psychopy.app.plugin_manager.dialog.EnvironmentManagerDlg(self)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\dialog.py", line 43, in __init__
    self.pluginMgr = PluginManagerPanel(self.notebook, dlg=self)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 258, in __init__
    self.pluginList = PluginBrowserList(self.splitter, stream=dlg.output)
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 488, in __init__
    self.populate()
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 496, in populate
    items = getAllPluginDetails()
  File "E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py", line 1249, in getAllPluginDetails
    f.write(serverPluginDatabase)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 8878: illegal multibyte sequence
`

**Comment by swg168** [comment] 2024-04-03 11:40
But when I use Psychopy 2023.2.3, I can successfully access the plugin list page.

**Comment by peircej** [comment] 2024-04-03 11:44
> But when I use Psychopy 2023.2.3, I can successfully access the plugin list page.

Oh now you're really confusing us! 🤣 

OK, but that may be useful information.  @TEParsons can cee what has changed in the meantime so we can come up with some guesses about how to get it working again on your network. I also wonder though if this is about the translation somehow

**Comment by swg168** [comment] 2024-04-03 11:52
I'm sorry for the misunderstanding caused by the translation. I re-explain my problem. When I use Psychopy2023.2.3 on the same computer, I can enter the plugin page and successfully refresh the plugin list, but for Psychopy 2023.2.3, even if I downloaded the Tobii EYETRACK plugin, I could not successfully call the hardware. This is an already existing problem. So I turned to psychopy2024.1.0, but I could only enter the plugin page without successfully refreshing the plugin list, let alone download the Tobii Eyetrack plugin.

**Comment by swg168** [comment] 2024-04-03 12:55
hello, I think I solved the problem.  Here is my step: I change the code in the E:\PsychoPy\lib\site-packages\psychopy\app\plugin_manager\plugins.py 1248 row ` with open(pluginDatabaseFile, 'w') as f:`  to ` with open(pluginDatabaseFile, 'w', encoding='utf-8') as f:`   and the plugin page jump the output:
![image](https://github.com/psychopy/psychopy/assets/109449633/4aabde4c-7aa7-46d4-b3b8-403427060333)

finally, I successfully got the plugin list:
![image](https://github.com/psychopy/psychopy/assets/109449633/d166ee07-e4d1-4fd2-8a0e-6b2a661c448a)

I hope my feedback will be helpful, thanks for your time.

**Comment by peircej** [comment] 2024-04-03 14:57
Ah, that's a great spot, well done for tracking it down 👏 
Would you like to put that in as a pull request (from the release branch to the release branch)? That way you can get credit for having found the fix - we like to give contributors credit for what they've done.

I'm very happy to put the fix in on your behalf though, if you aren't quite comfortable with git

**Comment by peircej** [comment] 2024-04-03 15:00
(just to be clear about your solution for others - the file is encoded with UFT-8 but this user's locale means that the python default is to attempt to use GBK (Chinese) encoding instead)

**Comment by swg168** [comment] 2024-04-04 00:00
Ok, I'm delighted to be able to contribute to the community, but I'm not very familiar with git. I would greatly appreciate it if you could do these for me.

**Closed as completed** 2024-04-30 11:00 UTC
Labels: 🐞 bug
