### ISSUE TITLE
Login to Pavlovia fails in PsychoPy3 on Linux Mint with Conda

### ISSUE THREAD

**Issue by diegodlh** [psychopy/psychopy#1979] opened 2018-08-23 17:05 UTC
Installed latest build (3.0.0b7) of PsychoPy3 in a conda environment.
My computer runs Linux Mint 17, and glib-networking is installed through package manager.
When trying to login to Pavlovia in PsychoPy, it fails with "TLS/SSL support not available; install glib-networking"

These are the steps I followed for installation
1) conda create -n psypy36 python=3.6
2) conda activate psypy36
3) conda install numpy scipy matplotlib pandas pyopengl pillow lxml openpyxl xlrd configobj pyyaml gevent greenlet msgpack-python psutil pytables requests[security] cffi seaborn wxpython cython pyzmq pyserial glib glib-networking-cos6-x86_64
4) pip install pyglet pysoundfile python-bidi moviepy pyosf astunparse zmq json-tricks pyparallel sounddevice pygame pysoundcard psychopy_ext psychopy
5) conda install -c conda-forge astunparse
6) installed build's downloaded zip file from GitHub through the PsychoPy interface

Let me know if you need further information to diagnose the problem.

**Comment by peircej** [comment] 2018-08-23 20:43
Could you post the complete error message so we know where the SSL problem originates? Might be in requests, might be in git-python etc.. Thanks

**Comment by diegodlh** [comment] 2018-08-23 21:04
Thank you for answering, Jon. When I click on menu Pavlovia.org > User > Log in to Pavlovia, a window opens which says:
Unable to load page
Problem occurred while loading the URL https://gitlab.pavlovia.org/oauth/authorize?client_id=4bb79f0356a566cd7b49e3130c714d9140f1d3de4ff27c7583fb34fbfac604e0&redirect_uri=https://gitlab.pavlovia.org/&response_type=token&state=a28f6ed5-8003-41b3-95e0-84ea38ac5d30
TLS/SSL support not available; install glib-networking

Please, let me know if you need further debug information. I would appreciate it if you could tell me if there is a way to launch the app with more verbose output.
Thanks again

**Comment by diegodlh** [comment] 2019-01-07 20:00
Sorry, @hoechenberger, I stopped using PsychoPy and moved to jsPsych because access to the source code of the server side scripts to self-run html scripts was denied (see https://discourse.psychopy.org/t/running-psychopy-3-0-0-html-on-your-own-server/5082/11). Maybe I misunderstood the admins, but I felt this wasn't a fair open source practice and decided to move to a more transparent project.

**Comment by hoechenberger** [comment] 2019-01-08 08:17
Hi @diegodlh, thanks for the info. In that case, I will close the issue.

**Comment by peircej** [comment] 2019-01-08 11:56
> Maybe I misunderstood the admins, but I felt this wasn't a fair open source practice and decided to move to a more transparent project.

Pavlovia.org is not open source. It's a service layer that we are providing on top of PsychoJS and PsychoPy. I don't think this is "unfair" or lacking transparency. It's providing more options than we previously had.

All the source code for PsychoJS is open source, so you could absolutely write your own data-saving PHP. We will probably provide something like this ourselves in the future but, as I said in the linked post, working on that just isn't one of our priorities (implementing features like movies and forms to PsychoJS is more important).

**Comment by andresimi** [comment] 2019-01-22 20:47
Hello @hoechenberger, the problem persists with PsychoPy installed through conda in Fedora 29

**Comment by kupiqu** [comment] 2020-04-07 14:34
This issue should be reopen as the problem is still there. @andresimi sees it in Fedora and I see it in an Ubuntu derivative.

**Comment by peircej** [comment] 2020-04-07 18:28
Could you provide a complete error message for us to work with?

**Comment by kupiqu** [comment] 2020-04-07 18:37
I'll try. Can you elaborate a bit how do I do that?

**Comment by peircej** [comment] 2020-04-07 19:21
When it fails to sync is there an error message? Coulfd you make sure the Coder view (or the new Runner view) is visible when you attempt to sync?

**Comment by kupiqu** [comment] 2020-04-07 19:35
The message is the same as above pretty much:

![image](https://user-images.githubusercontent.com/3875196/78711604-3b8a8880-78e5-11ea-9745-ef35a7727992.png)

I don't see any error message in the terminal.

> Coulfd you make sure the Coder view (or the new Runner view) is visible when you attempt to sync?

Both of them are opened when I try to login to pavlovia for the first time.

**Comment by kupiqu** [comment] 2020-04-08 15:25
I workarounded the issue by moving out \*gio\* and \*gnutls\* libraries from my conda environment:

```
mkdir -p CONDA_PATH/envs/ENV_NAME/lib_orig

mv CONDA_PATH/envs/ENV_NAME/lib/*gio* CONDA_PATH/envs/ENV_NAME/lib_orig/

mv CONDA_PATH/envs/ENV_NAME/lib/*gnutls* CONDA_PATH/envs/ENV_NAME/lib_orig/
```

I got the hint from: https://github.com/Parisson/TimeSide/blob/master/Dockerfile

```
# Link glib-networking with Conda to fix missing TLS/SSL support in Conda Glib library
#RUN rm /opt/miniconda/lib/libgio* &&\
#    ln -s /usr/lib/x86_64-linux-gnu/libgio* /opt/miniconda/lib/
```

However, this was not enough in my case and I had to also get rid of gnutls libs.

I assume after that conda's Psychopy is using system's glib-networking to communicate with Pavlovia, and I could successfully login in Pavlovia within Psychopy.

Not sure this will have other side effects though.

**Comment by hoechenberger** [comment] 2020-04-08 20:55
Interesting. We should report this upstream to the conda-forge folks.

**Comment by nik0lai** [comment] 2020-05-19 14:21
I have the same problem with PsychoPy3 installed via the .yml file from the instructions in a machine with Ubuntu 18.04.4 LTS. As suggested by @kupiqu, this worked for me:

```
mkdir -p CONDA_PATH/envs/ENV_NAME/lib_orig
mv CONDA_PATH/envs/ENV_NAME/lib/*gio* CONDA_PATH/envs/ENV_NAME/lib_orig/
mv CONDA_PATH/envs/ENV_NAME/lib/*gnutls* CONDA_PATH/envs/ENV_NAME/lib_orig/
```

**Comment by peircej** [comment] 2021-08-12 11:20
I'm closing this again as a problem upstream

**Closed by peircej** 2021-08-12 11:20 UTC
Labels: needs upstream fix, conda
