### ISSUE TITLE
Limit on height of TextStim in 1.85.2

### ISSUE THREAD

**Issue by eddjberry** [psychopy/psychopy#1463] opened 2017-07-17 10:39 UTC
There seems to be a strange limit on the height of a visual.TextStim() that will be displayed in PsychoPy 1.85.2.

Here's an example:

```
from psychopy import core, visual

win = visual.Window([1920, 1080], fullscr=True, allowGUI= False, units = "height")

# make the text
t1 = visual.TextStim(win, text = "0.02", height = 0.02, pos = [-0.2,0], color = "black")
t2 = visual.TextStim(win, text = "0.04", height = 0.04, pos = [-0.1,0], color = "black")
t3 = visual.TextStim(win, text = "0.06", height = 0.06, pos = [0.1,0], color = "black")
# this last one doesn't display
t4 = visual.TextStim(win, text = "0.08", height = 0.08, pos = [0.3,0], color = "black")

#draw the text
t1.draw()
t2.draw()
t3.draw()
t4.draw()

# flip the window
win.flip()

# wait 2s
core.wait(2)
```

When I run this the final TextStim ("0.08") doesn't display. These issues started after I updated from 1.84.2. My OS is Win7, if that's relevant.

Everything displays fine on my Linux Mint 18.1 machine running PsychoPy 1.83.04

**Comment by mmagnuski** [comment] 2017-07-17 21:02
duplicate of #1385
Please, report your problem in that issue - would be easier to track down any commonalities.

more generally:
I also have this problem and it keeps me from updating to current psychopy version. :(
If that makes this issue more urgent - I can try replicating this on all PCs I have access to.

**Closed** 2017-08-10 11:04 UTC
