### ISSUE TITLE
The Release v2021.2.0 crashes in mac os.

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychopy#4081] opened 2021-06-24 04:48 UTC
I guess it's some link issue. Referencing user directory supposed to used in compilation.

```
Traceback (most recent call last):
  File "/Applications/PsychoPy_2021_2_0.app/Contents/Resources/lib/python3.6/psychopy/app/runner/runner.py", line 349, in loadBuilderDemos
  File "/Applications/PsychoPy_2021_2_0.app/Contents/Resources/lib/python3.6/psychopy/app/runner/runner.py", line 97, in addTask
  File "/Applications/PsychoPy_2021_2_0.app/Contents/Resources/lib/python3.6/psychopy/app/runner/runner.py", line 823, in addTask
wx._core.wxAssertionError: C++ assertion ""litem >= 0 && (size_t)litem < GetItemCount()"" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/generic/listctrl.cpp(3649) in SetItemState(): invalid list ctrl item index in SetItem
```

**Comment by peircej** [comment] 2021-06-24 11:00
hmmm. Thanks for getting the stacktrace out
Looks like an issue with reloading the previous files into Runner view. Could you clear your userprefs file (or move it to a different name) to see if that fixes it? Then we can try and work out what went wrong if so

**Comment by iPsych** [comment] 2021-06-24 19:34
I think it's similar to https://github.com/psychopy/psychopy/issues/3060 issue.

**Comment by iPsych** [comment] 2021-06-26 02:31
@peircej 
Still same, with 2.0.1, the error message is same with 
https://github.com/psychopy/psychopy/issues/2823
The crash of PTB main thread in High Sierra. (Tested in three different system in 10.13.6, Mac Pro 2013, MBP 2014, Mac Mini 2012).

**Comment by peircej** [comment] 2021-06-28 08:45
I don't see the error message you report in either of those issues, and 3060 has been fixed (that was a packaging/code-signing issue on newer versions of macOS. 

I don't understand though, if this is occurring at startup why any files are being loaded if you've cleared out your user prefs. 🤔  If this is failing on 3 systems, I wonder why I can't reproduce it. Is there anything else you're doing before this happens?

**Comment by peircej** [comment] 2021-06-28 08:46
Also, when you say you tested on those 3 different macs, were they all running High Sierra? I haven't used that in a while so maybe that's the issue

**Comment by iPsych** [comment] 2021-06-28 08:49
@peircej Yes, all High Sierra. I will test in Mojave and report today.

**Comment by bollaking** [comment] 2021-06-28 09:31
How can I get the stacktrace. I get a similar crash when I run but it is silent. All I get is the Apple notification that a program has crashed. PsychoPy itself does not crash just the thread running the experiment.  I maybe too bleeding edge as I am on Big Sur and I have seen many things on the internet regarding xCode 12.  Here is the Apple report if it helps?
[dump.txt](https://github.com/psychopy/psychopy/files/6725117/dump.txt)

**Comment by iPsych** [comment] 2021-07-02 04:13
@peircej
The head of full error message is below. 
It seems the crash is related to LIBDISPATCH.

I get the same error message in Catalina too.
Both machines are Mac Book Pro 2014, (tested in high sierra mac pro 2012, Catalina Mac pro 2013 too...)

```
Process:               python [5255]
Path:                  /Volumes/*/PsychoPy.app/Contents/MacOS/python
Identifier:            org.opensciencetools.psychopy
Version:               2021.2.0 (2021.2.0)
Code Type:             X86-64 (Native)
Parent Process:        PsychoPy [5212]
Responsible:           python [5255]
User ID:               501

Date/Time:             2021-07-02 13:11:30.201 +0900
OS Version:            Mac OS X 10.13.6 (17G14033)
Report Version:        12
Anonymous UUID:        D8BA7AA7-0D79-1622-F233-9909F127720A


Time Awake Since Boot: 30000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  PTB mainthread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread

```

**Comment by giuliaccc222** [comment] 2021-07-03 14:10
Hi, I get the same error on my Macbook Pro too (2019 - running Big Sur v 11.2.1). It happens every time I run an experiment from Builder (see screenshot). I downgraded to Psychopy 2021.1.4 and it seems to work, but it would be great to have the latest version to use the new eye tracking component integrated into Builder.

<img width="851" alt="Schermata 2021-07-03 alle 14 59 58" src="https://user-images.githubusercontent.com/69050830/124356778-db7db180-dc0f-11eb-8357-10c36e2c574e.png">

**Comment by iPsych** [comment] 2021-07-04 02:49
@giuliaccc222 exactly same error. I've excluded software issues, since one of the tested system is dedicated to experiment and not 3rd party system utils like istats... etc.
One remaining possibility in software level is the exists of brew. Do you have homebrew in your system?

**Comment by iPsych** [comment] 2021-07-04 11:41
@peircej 
I found below, and tried to command to run 
`/Applications/PsychoPy3.app/Contents/MacOS/python -m psychopy.app.psychopyApp
`but below error happens.
"Users/robind/" is pops up in the error repeatedly. Is there any path issue while compiling?
'robind' is mentioned in several other issues,
https://github.com/psychopy/psychopy/pull/2563
https://github.com/psychopy/psychopy/issues/3065

https://github.com/psychopy/psychopy/issues/3060

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 104, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 190, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 329, in onInit
    self.showCoder(fileList=scripts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 493, in showCoder
    files=fileList, app=self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psychopy/app/coder/coder.py", line 1333, in __init__
    self.paneManager.LoadPerspective(self.appData['auiPerspective'])
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py36/Phoenix/ext/wxWidgets/src/aui/framemanager.cpp(1521) in LoadPaneInfo(): Bad Perspective String
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py36/Phoenix/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Segmentation fault: 11
```

**Comment by peircej** [comment] 2021-07-06 17:49
There are several different error messages going on here. @iPsych your first one was about the runner. Your most recent one was about the Coder and it's a different error message. You haven't said what you're actually doing when either of these occur (which might help me to reproduce it locally).

@giuliaccc222 and @bollaking I can replicate what looks like the issue you have (at the point of studies running not in the app) and currently investigating.

**Comment by iPsych** [comment] 2021-07-09 03:01
@peircej, Yes, the first one is issue on runner from builder, and the recent one is what I found while searching 'robind'.
Isn't this the path issue related on libraries and frameworks of MacOS?

**Comment by jfkominsky** [comment] 2021-07-13 13:54
I've been encountering related errors that are different flavors of memory access issues, primarily in the context of accessing complex dictionaries that contain things like media files or paths (yes, this is all PyHab stuff). There is something weird going on with memory allocation or protection or something, because my errors are always things like "KERN_PROTECTION_FAILURE at 0x0000000102b61000" or "KERN_INVALID_ADDRESS at 0x0000000000000007". I suspect this is a MacOS issue but I cannot begin to fathom how it works.

2017 Macbook Pro, Catalina 10.15.7

**Comment by jfkominsky** [comment] 2021-07-16 14:57
I think I have at least pinned this down into something reproducible. I created a version of the vlcmoviestim coder demo and found a few different patterns of behavior. Let me start with the base code I used:

```
from __future__ import division
import os
from psychopy import visual, core, event
from psychopy import logging
logging.console.setLevel(logging.DEBUG)

# open a window to display the video
win = visual.Window([800, 800], fullscr=False)

# Setting videopath not shown because it seems to be arbitrary what file I use

mov = visual.VlcMovieStim(win, videopath,
    size=600,  # set as `None` to use the native video size
    pos=[0, 0],  # pos specifies the /center/ of the movie stim location
    flipVert=False,  # flip the video picture vertically
    flipHoriz=False,  # flip the video picture horizontally
    loop=False,  # replay the video when it reaches the end
    autoStart=False, # do not start the video automatically when first drawn
    name="testmovie1")  

# Step 1: Let's try to get it to render the first frame.
#core.wait(.5) 
#event.waitKeys()
mov.play() 

mov.draw()
win.flip()
mov.draw()
win.flip() 

mov.pause()

event.waitKeys()
# main loop, will exit automatically when the movie is finished
mov.play()
while not mov.isFinished:
    #etc...
```

This code, as written, will show nothing until a key is pressed, at which point it will play the movie just fine. So right off the bat, it's ignoring that initial 'play' command and the first two frames.

When I uncomment the "core.wait(.5)" at the top, it crashes after the wait is finished, gives no errors in the PsychoPy window, but throws an Apple crash report with the following:

> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x000003e900007530
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Segmentation fault: 11
> Termination Reason:    Namespace SIGNAL, Code 0xb
> Terminating Process:   exc handler [52337]
> 
> VM Regions Near 0x3e900007530:
>     ATS (font support)     0000000128162000-0000000128163000 [    4K] rw-/rwx SM=PRV  
> --> 
>     STACK GUARD            000070000f9df000-000070000f9e0000 [    4K] ---/rwx SM=NUL  stack guard for thread 6
> 
> Application Specific Information:
> Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.

If I leave the core.wait out but uncomment the first event.waitKeys(), it's 50/50 whether it crashes or not. When it doesn't crash, it doesn't render anything.

Notably, in all of these crashes, I have the logger set to give me debug info, and the logs only get this:

> 4.1665     DEBUG     Spawning new VLC instance ...
> 4.5125     DEBUG     VLC instance created.
> 4.5202     INFO     Video is 1280x720, duration -1, fps 0.0

But when it plays successfully I get this:

> 4.1323     DEBUG     Spawning new VLC instance ...
> 4.4343     DEBUG     VLC instance created.
> 4.4428     INFO     Video is 1280x720, duration -1, fps 0.0
> 4.4438     EXP     Created testmovie1 = VlcMovieStim(__class__=type(...), autoLog=True, autoStart=True, color=UNKNOWN, colorSpace=UNKNOWN, depth=0.0, filename=str(...), flipHoriz=False, flipVert=False, interpolate=True, loop=False, name='testmovie1', noAudio=UNKNOWN, opacity=1, ori=0.0, pos=array([0., 0.]), size=array([600., 600.]), units='pix', volume=-1, win=Window(...)) 
> 4.8839     DATA     Keypress: space

So first off, it's not _logging_ the VlcMovieStim object until play is called, which is weird, even though it seems to create the object much earlier. Second, the base error really seems to be something about accessing the external file in memory.

This seems like it's the product of some kind of low-level interaction between PsychoPy and MacOS, but I honestly don't know where to start in figuring out how to fix it.

All of this on PsychoPy Standalone 2020.2.0, though I've also tried it with a separate python 3 environment and gotten pretty much the same behavior.

**Comment by mdcutone** [comment] 2021-07-16 22:02
Thanks for trying to get to the bottom of this. I'm quite puzzled by this line Apple error log as it seems unrelated to the problem:

```
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

My suspicion is that `python-vlc` is using `libcrypto` somewhere and it's failing when trying to access it.

**Comment by peircej** [comment] 2021-07-23 12:43
Could you try with 2021.2.1 (just released)?

There was certainly one issue with launching the app that turned out to be occurring during the Apple Code Signing step of the building - it turns out that the psychtoolbox dylib that was installed had been compiled with a compiler that didn't support code sign so it was being stripped out.

For crypto we now explicitly include the python cryptography package whereas before that was implicit and maybe not therefore including the correct dylib (relying on one that had been installed on the OS?)

Sorry everyone that this is so painful - macOS is just nasty to develop for because of the way it gives us essentially useless errors and leaves us to fix the code by trial and error! 😬 As a user I love my mac, as a developer it sometimes drives me nuts!!

**Comment by jfkominsky** [comment] 2021-07-23 13:26
Just got 2021.2.1 and tried it, but I'm afraid it's the exact same as it was before. When it works it behaves as describes, when it crashes it crashes with the same error:

```
Crashed Thread:        16

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000090
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [25084]

VM Regions Near 0x90:
--> 
    __TEXT                 0000000103c7c000-0000000103c7d000 [    4K] r-x/rwx SM=COW  /Applications/PsychoPy.app/Contents/MacOS/python

Application Specific Information:
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

**Comment by iPsych** [comment] 2021-07-26 15:34
@peircej Thanks. I just tested 2021.2.1. The experiment runs properly in High Sierra and Catalina.
I cannot agree more about your feeling toward recent MacOS development.

**Comment by peircej** [comment] 2021-08-12 15:39
OK, I'm closing this issue as the original posted issue is fixed (crashing when launching on macOS)

By the way the new 2021.2.3 now fixes the annoying frozen-in-the-dock issue too 🥳

@jfkominsky it looks like your issue is a specific thing to do with the VLC movies. Let's move that discussion to a separate issue so that we have only one bug to fix per thread. thx

**Closed as completed by peircej** 2021-08-12 15:39 UTC
Labels: 🐞 bug, 📦 packaging
