### ISSUE TITLE
Refresh-rate is not in line with system refresh rate

### ISSUE THREAD

**Issue by fahrenfort** [psychopy/psychopy#896] opened 2015-05-05 08:33 UTC
Psychopy seems to be doing something odd to the refresh-rate of our 120 Hz systems. When I run the benchmarking tool, everything is running nice and dandy at 120 Hz (flip time 8.33 ms). However, when I run my experiment, Psychopy reports that it is running at 60 fps in the log file, even though the resolution of the monitor is set to 120 Hz, as is confirmed by the benchmarking tool. More strangely even, the _actual_ resolution (flip-time) seems to be running either at 40 hz (flip time 25 ms) or 60 Hz (flip time 16.66 ms), depending on the system on which I'm testing, but 60 fps is reported in the log file regardless. I cannot find the source of the problem. It is definitely something related to the graphics cards we are using (an Nvidia GeForce 210, but I've also seen it on GeForce GT 720). A similar issue was reported by somebody else in Google groups:
https://groups.google.com/forum/#!topic/psychopy-users/HzxSKvupX-U
where somebody mentioned that they solved it by setting useFBO=false. If I try this (which unfortunately I do not seem to be able to do in the builder view), the situation changes, such that the system that was previously running at 40Hz now runs at 60Hz when running an experiment, and that the system that was using 60 Hz now runs at 120 Hz. In both cases, the system refresh rate is set to 120 Hz though as confirmed by PsychoPy's benchmarking tool. Is there any way I can force PsychoPy to adopt a certain refresh rate? Could there be a bug somewhere that impacts the refresh rate on some systems, possibly related to FBO? Or some other buffer-related influence on the refresh rate?

**Comment by lindeloev** [comment] 2015-05-10 11:45
The fact that 60Hz and 40Hz are divisors of 120Hz makes me think that the prime suspect is that the additional processing in your experiment script (compared to the very simple timesByFrames demo) causes the system to miss frames.

Assuming that you're using code and that you loop over win.flip(), to determine if the above is the case, try using ``core.Clock()`` around all the other stuff inf the loop than the win.flip(). E.g.

```python
from psychopy import core
my_clock = core.Clock()
for frame in range(60):  # 0.5 secs on 120Hz
    my_clock.reset()
    stim.pos += 0.01
    stim.ori *= 0.01
    stim.draw()
    #win.flip()
    response = event.getKeys()
    print 'processing for this frame took', my_clock.getTime() * 1000, 'ms'
```

**Comment by Sjocolaatje** [comment] 2015-05-11 07:42
Hi Jonas, thanks for your reply! I have tried the above code with win.flip() on, and I can confirm the problem has to do with useFBO. When creating a window using useFBO=true, I get a frame duration of 16.66 ms, despite the fact that the system refresh resolution is set to 120Hz. As soon as I set useFBO =false, the frame rate drops to the 'correct' 8.33 ms. Does anybody have a clue what the problem with useFBO could be to instill this kind of behavior, even when using a simple script as the above?

**Comment by suddhasourav** [comment] 2015-05-11 12:33
http://oldforums.eveonline.com/?a=topic&threadID=1018869

Very interesting to note that gamers also have had the same problem. Apparently some operations on FBOs are expensive, and can cause one to miss frames. I wonder whether this problem should be visible to end-users though! Can't we just disable it by default then?

**Comment by Sjocolaatje** [comment] 2015-05-11 12:42
The problem might be more pervasive than simply dropping frames though. I would not expect any frame dropping in a script as simple as the above? I don't know anything about FBO, but could it be that Psychopy or the graphics card driver actually (re)sets the refresh rate when FBO is on? In builder view, the logfiles report a different fps when FBO is on versus when it is off, despite no other changes being made to the scripts anywhere. I haven't checked yet where it grabs the fps information, but unless the fps are computed dynamically during the script useFBO actually impacts the monitor refresh rate directly. Regardless, it would be nice if it would be possible to somehow set the FBO variable in the builder view.

**Comment by lindeloev** [comment] 2015-05-11 12:59
If useFBO=True adds a processing penalty of around 8-14 ms for each flip,
then it would cause the frame rate to 1/2, i.e. from 120 to 60 Hz. If it's
around 16-24 ms, then it would reduce to 1/3, i.e. 40 Hz. I know nothing
about FBO. Just wanted to point out that your dropped frames could be
explained by processing time alone. But may of course also be caused by
other factors. I hope someone more knowledgeable drops by with a
clarification or solution for you :-)

______________________________

Jonas Kristoffer Lindeløv
cnru.dk/people/jonas-lindeloev

**Comment by peircej** [comment] 2015-05-11 15:48
Hi Sjocolaatje,

You haven't told us what your operating system is. On linux there are 
many potential settings to work through and try to identify what's going 
on, but also on windows the opengl panel of the graphics card driver 
settings typically has many options.

what are you using?

Jon

On 11/05/15 13:59, Jonas Lindeløv wrote:
> If useFBO=True adds a processing penalty of around 8-14 ms for each flip,
> then it would cause the frame rate to 1/2, i.e. from 120 to 60 Hz. If it's
> around 16-24 ms, then it would reduce to 1/3, i.e. 40 Hz. I know nothing
> about FBO. Just wanted to point out that your dropped frames could be
> explained by processing time alone. But may of course also be caused by
> other factors. I hope someone more knowledgeable drops by with a
> clarification or solution for you :-)
>
> ______________________________
>
> Jonas Kristoffer Lindeløv
> cnru.dk/people/jonas-lindeloev
>
> On Mon, May 11, 2015 at 2:42 PM, Sjocolaatje <notifications@github.com>
> wrote:
>
> > The problem might be more pervasive than simply dropping frames 
> though. I
> > would not expect any frame dropping in a script as simple as the 
> above? I
> > don't know anything about FBO, but could it be that Psychopy or the
> > graphics card driver actually (re)sets the refresh rate when FBO is 
> on? In
> > builder view, the logfiles report a different fps when FBO is on versus
> > when it is off, despite no other changes being made to the scripts
> > anywhere. I haven't checked yet where it grabs the fps information, but
> > unless the fps are computed dynamically during the script useFBO 
> actually
> > impacts the monitor refresh rate directly. Regardless, it would be 
> nice if
> > it would be possible to somehow set the FBO variable in the builder 
> view.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/psychopy/psychopy/issues/896#issuecomment-100893886>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/896#issuecomment-100898638>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment] 2015-05-11 15:51
Yes, it is calculated at the beginning of the script by flipping the 
window and seeing how long it takes for the the screen refresh to occur.

I've said to several of these emails before that PsychoPy doesn't do 
anything itself to control refresh rates; it merely flips and waits for 
the flip to occur.

Jon

On 11/05/15 13:59, Jonas Lindeløv wrote:
> I haven't checked yet where it grabs the fps information, but
> > unless the fps are computed dynamically during the script useFBO 
> actually
> > impacts the monitor refresh rate directly.

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by Sjocolaatje** [comment] 2015-05-11 17:06
Hi Jon, thanks, for responding. It's windows. I've tried many things in the settings panel of the graphics card to no avail. If psychopy does not control the refresh rate it's obviously something with the FBO that causes the dropping of frames. What is this useFBO setting anyway? Is it an OpenGL setting? Maybe something to disable by default if it causes the refresh rate to drop to 40 when it should be 120 (at least in some instances, as also noted by other users)? I should add that our computers are not particularly old, and though our graphics cards are low end, they definitely accommodate 120 hz under normal circumstances and using other stimulus presentation packages...

**Comment by peircej** [comment] 2020-11-24 14:16
I'm closing this for now. I think it indicates a performance issue, but not a common one and not easy to debug. We are gradually improving OpenGL performance so hopefully if it it still an issue it will have gotten less at least

**Closed by peircej** 2020-11-24 14:16 UTC
Labels: involves opengl, library, platform windows
