### ISSUE TITLE
Unable to use iohub's launchHubServer() in Linux Mint 19.1, Psychopy v3.0.7

### ISSUE THREAD

**Issue by riftguardian** [psychopy/psychopy#2386] opened 2019-04-02 20:24 UTC
Hello,

When attempting only to perform (cut from iohub tutorial):
```
from psychopy.iohub import launchHubServer
io = launchHubServer()
```

I receive the following error message:
```
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 476, in _createAllRuntimeInfoDicts
    runtime_info['retrace_rate'] = mode.rate
AttributeError: 'NoneType' object has no attribute 'rate'
Error during device creation ....
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 637, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 801, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 58, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 497, in _addRuntimeInfoToDisplayConfig
    runtime_info = self._getRuntimeInfoByIndex(self.device_number)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 403, in _getRuntimeInfoByIndex
    display_index >= cls.getDisplayCount()):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 99, in getDisplayCount
    return len(cls._computer_display_runtime_info_list)
TypeError: object of type 'NoneType' has no len()
Error during device creation ....
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 637, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 801, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 58, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 497, in _addRuntimeInfoToDisplayConfig
    runtime_info = self._getRuntimeInfoByIndex(self.device_number)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 403, in _getRuntimeInfoByIndex
    display_index >= cls.getDisplayCount()):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/display/__init__.py", line 99, in getDisplayCount
    return len(cls._computer_display_runtime_info_list)
TypeError: object of type 'NoneType' has no len()

>During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 572, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/server.py", line 650, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
_addDeviceView: Error adding class. 
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/client/__init__.py", line 1083, in _addDeviceView
    d = local_class(self, dev_cls_name, dev_config)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/client/keyboard.py", line 165, in __init__
    self._reporting = self.isReportingEvents()
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/client/__init__.py", line 143, in __getattr__
    raise AttributeError(self, name)
AttributeError: (<psychopy.iohub.client.keyboard.Keyboard object at 0x7fcc5b55f860>, 'isReportingEvents')
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
Process finished with exit code 0
```

Going to line 476 of display/__init__.py reveals the following section of code:
```
    @classmethod
    def _createAllRuntimeInfoDicts(cls):
        runtime_info_list = []
        try:
            #try getting screen info using pyglet 1.2.x
            import pyglet
            default_screen = pyglet.canvas.get_display().get_default_screen()
            dx, dy = default_screen.x, default_screen.y
            dw, dh = default_screen.width, default_screen.height
            dbounds = (dx, dy, dx + dw, dy + dh)
            pyglet_screens = pyglet.canvas.get_display().get_screens()
            display_count = len(pyglet_screens)
            for i in range(display_count):
                d = pyglet_screens[i]
                mode = d.get_mode()
                x, y, w, h = d.x, d.y, d.width, d.height
                runtime_info = dict()
                runtime_info['index'] = i
                runtime_info['pixel_width'] = w
                runtime_info['pixel_height'] = h
                runtime_info['bounds'] = (x, y, x + w, y + h)
                runtime_info['retrace_rate'] = mode.rate
                runtime_info['bits_per_pixel'] = mode.depth
                runtime_info['primary'] = runtime_info['bounds'] == dbounds
                if mode and mode.width > 0 and mode.height > 0:
                    runtime_info['pixel_resolution'] = mode.width, mode.height
                else:
                    runtime_info['pixel_resolution'] = w, h
                runtime_info_list.append(runtime_info)
            return runtime_info_list
        except Exception:
            printExceptionDetailsToStdErr()
```

**Which brings me to the focus of the issue:**
The problem I observed was that d.get_mode() produces mode = None, which messes up the later code. This makes me think there's an issue with pyglet.

Isolating the pyglet code, I can show the display variables:
![pygletvars](https://user-images.githubusercontent.com/48695308/55433225-e5149c80-5562-11e9-8275-04c8e3ae7ef9.png)

I'm not sure where to proceed from here... is there some additional configuration I need to set for my monitor screens?

I am using a conda python 3.5 environment freshly installed with PsychoPy v3.0.7 via Git. I have Linux Mint 19.1, and use a nvidia GPU 1080 (currently using nvidia driver). I have installed the following packages:
```
arabic-reshaper           2.0.14                    <pip>
asn1crypto                0.24.0                    <pip>
astunparse                1.6.2                     <pip>
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.8.24                py35_1  
cffi                      1.12.2                    <pip>
chardet                   3.0.4                     <pip>
configparser              3.7.4                     <pip>
cryptography              2.6.1                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.0                     <pip>
esprima                   4.0.1                     <pip>
et-xmlfile                1.0.1                     <pip>
expat                     2.2.6                he6710b0_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
freetype-py               2.1.0.post1               <pip>
fribidi                   1.0.5                h7b6447c_0  
future                    0.17.1                    <pip>
gettext                   0.19.8.1             hd7bead4_3  
gevent                    1.4.0                     <pip>
gitdb2                    2.0.5                     <pip>
GitPython                 2.1.11                    <pip>
glib                      2.56.2               hd408876_0  
graphite2                 1.3.13               h23475e2_0  
greenlet                  0.4.15                    <pip>
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
harfbuzz                  1.8.8                hffaf4a1_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                       <pip>
imageio                   2.5.0                     <pip>
imageio-ffmpeg            0.2.0                     <pip>
jdcal                     1.4                       <pip>
jpeg                      9b                   h024ee3a_2  
json-tricks               3.13.1                    <pip>
kiwisolver                1.0.1                     <pip>
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libglu                    9.0.0                hf484d3e_1  
libpng                    1.6.36               hbc83047_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
matplotlib                3.0.3                     <pip>
mock                      2.0.0                     <pip>
moviepy                   1.0.0                     <pip>
msgpack                   0.6.1                     <pip>
msgpack-numpy             0.4.4.2                   <pip>
msgpack-python            0.5.6                     <pip>
ncurses                   6.1                  he6710b0_1  
numexpr                   2.6.9                     <pip>
numpy                     1.16.2                    <pip>
openpyxl                  2.6.2                     <pip>
openssl                   1.0.2r               h7b6447c_0  
pandas                    0.24.2                    <pip>
pango                     1.42.4               h049681c_0  
pbr                       5.1.3                     <pip>
pcre                      8.43                 he6710b0_0  
Pillow                    5.4.1                     <pip>
pip                       10.0.1                   py35_0  
pip                       19.0.3                    <pip>
pixman                    0.38.0               h7b6447c_0  
proglog                   0.1.9                     <pip>
psutil                    5.6.1                     <pip>
PsychoPy                  3.0.7                     <pip>
pycparser                 2.19                      <pip>
pygame                    1.9.5                     <pip>
pyglet                    1.3.2                     <pip>
PyOpenGL                  3.1.0                     <pip>
pyOpenSSL                 19.0.0                    <pip>
pyosf                     1.0.5                     <pip>
pyparallel                0.2.2                     <pip>
pyparsing                 2.3.1                     <pip>
PyQt5                     5.12.1                    <pip>
PyQt5_sip                 4.19.15                   <pip>
pyserial                  3.4                       <pip>
python                    3.5.6                hc3d631a_0  
python-bidi               0.4.0                     <pip>
python-dateutil           2.8.0                     <pip>
python-gitlab             1.8.0                     <pip>
pytz                      2018.9                    <pip>
PyYAML                    5.1                       <pip>
pyzmq                     18.0.1                    <pip>
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                    <pip>
scipy                     1.2.1                     <pip>
setuptools                40.2.0                   py35_0  
six                       1.11.0                   py35_1  
six                       1.12.0                    <pip>
smmap2                    2.0.5                     <pip>
sounddevice               0.3.13                    <pip>
SoundFile                 0.10.2                    <pip>
sqlite                    3.27.2               h7b6447c_0  
tables                    3.5.1                     <pip>
tk                        8.6.8                hbc83047_0  
tqdm                      4.31.1                    <pip>
urllib3                   1.24.1                    <pip>
wheel                     0.31.1                   py35_0  
wxpython                  4.0.3            py35h76a34b6_0  
xlib                      0.21                      <pip>
xlrd                      1.2.0                     <pip>
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3 
```
Help is appreciated, thank you in advance!

**Comment by peircej** [comment] 2019-04-03 12:57
Thanks for the detailed bug report. We'll need to look into this (maybe with @isolver )
My first idea of how to progress is to see what happens if mode is ignored - you could move the lines 
```python
                runtime_info['retrace_rate'] = mode.rate
                runtime_info['bits_per_pixel'] = mode.depth
```
so that they come inside the if statement below (`if mode and mode.width...`)

**Comment by isolver** [comment] 2019-04-03 13:08
Let me test it again with the latest source on my Mint Linux setup; it was working a week or two ago. I was using the system python3 though, not anaconda. Not sure if that could make a difference.

**Comment by isolver** [comment] 2019-04-03 18:21
I am able to run demos/coder/iohub/launchHub.py without error on Mint Linux 19.1 and the latest psychopy source if I use the system python3. See my comments on getting it running at the end of #2326. It looks like you are using pyglet 1.3.2, which is the version I also needed to use so that should be OK.

Can you check if you have the python3-xlib package installed

pip3 install python3-xlib

Thanks

**Comment by isolver** [comment] 2019-04-13 11:29
Is this still an open issue? As mentioned above I was not able to reproduce on my setup using the latest psychopy master branch. 
Thank you.

**Comment by riftguardian** [comment] 2019-04-13 16:19
I was not able to get it to work, even after reinstalling it in another environment with install instructions per isolver. I tried moving the code as piercej suggested, and received the following error:

>/home/riftkun/.conda/envs/psypy3/bin/python /home/riftkun/PycharmProjects/test0/testfile.py
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/pyXHook.py", line 236, in run
    self.record_dpy.record_enable_context(self.ctx, self.processevents)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/ext/record.py", line 238, in enable_context
    context = context)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/ext/record.py", line 215, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1481, in __init__
    self.reply()
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1493, in reply
    self._display.send_and_recv(request = self._serial)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/Xlib/ext/record.py", line 219, in _parse_response
    self._callback(r)
  File "/home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/iohub/devices/pyXHook.py", line 294, in processevents
    if not len(reply.data) or ord(reply.data[0]) < 2:
TypeError: ord() expected string of length 1, but int found

>Process finished with exit code 0

I also installed the standalone 3.0.5 installation on Windows 10, and still cannot run iohub. In this case running the following stalls out, and nothing happens:
> from psychopy.iohub import launchHubServer
io = launchHubServer()
print('test')

Where the error is:
> ##### Running: C:\Program Files (x86)\PsychoPy3\Lib\site-packages\psychopy\demos\coder\iohub\test.py #####
>Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy3\Lib\site-packages\psychopy\demos\coder\iohub\test.py", line 5, in <module>
    io = launchHubServer()
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1

Sorry for the previous lack of communication. Thank you.

**Comment by isolver** [comment] 2019-04-13 16:52
Thanks for the feedback. I am wondering if you were testing with an older version of the source. The error:

> ackages/psychopy/iohub/devices/pyXHook.py", line 294, in processevents
> if not len(reply.data) or ord(reply.data[0]) < 2:
> TypeError: ord() expected string of length 1, but int found

does not match up with the current psychopy/psychopy master source. For example psychopy/iohub/devices/pyXHook.py", line 294 should be:

[if not len(reply.data): # or ord(reply.data[0]) < 2:](https://github.com/psychopy/psychopy/blob/master/psychopy/iohub/devices/pyXHook.py)

Would you mind getting the latest psychopy/psychopy/ master branch and install that into the env you are testing with?

Thank you.

**Comment by riftguardian** [comment] 2019-04-13 17:29
Previously I used:
>pip install git+https://github.com/psychopy/psychopy@3.0.7

This time I used (new environment):
>/home/riftkun/.conda/envs/psycho/bin/python3.5 setup.py install

I ran into similar issues with psychopy running iohub:
>##### Running: /home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/demos/coder/iohub/test.py #####
>Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 476, in _createAllRuntimeInfoDicts
    runtime_info['retrace_rate'] = mode.rate
AttributeError: 'NoneType' object has no attribute 'rate'
Error during device creation ....
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 637, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 804, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 58, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 497, in _addRuntimeInfoToDisplayConfig
    runtime_info = self._getRuntimeInfoByIndex(self.device_number)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 403, in _getRuntimeInfoByIndex
    display_index >= cls.getDisplayCount()):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 99, in getDisplayCount
    return len(cls._computer_display_runtime_info_list)
TypeError: object of type 'NoneType' has no len()
Error during device creation ....
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 637, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 804, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 58, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 497, in _addRuntimeInfoToDisplayConfig
    runtime_info = self._getRuntimeInfoByIndex(self.device_number)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 403, in _getRuntimeInfoByIndex
    display_index >= cls.getDisplayCount()):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/display/__init__.py", line 99, in getDisplayCount
    return len(cls._computer_display_runtime_info_list)
TypeError: object of type 'NoneType' has no len()

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 572, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 650, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

>GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
_addDeviceView: Error adding class. 
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/client/__init__.py", line 1092, in _addDeviceView
    d = local_class(self, dev_cls_name, dev_config)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/client/keyboard.py", line 165, in __init__
    self._reporting = self.isReportingEvents()
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/client/__init__.py", line 139, in __getattr__
    if name in self._methods:
TypeError: argument of type 'int' is not iterable
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None

So I used piercej's advice again, and ran into the following:
>##### Running: /home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/demos/coder/iohub/test.py #####
>Error during device creation ....
>Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 572, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 703, in createNewMonitoredDevice
    from .devices import pyXHook
  File "/home/riftkun/.conda/envs/psycho/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/pyXHook.py", line 52, in <module>
    from Xlib import X, display
ImportError: No module named 'Xlib'
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None

Using 'pip3 list' shows that I have:
>python-xlib (0.20)
python3-xlib (0.15)

So I don't understand the "no module named 'Xlib'" issue being returned.

Thank you for the fast response.

**Comment by isolver** [comment] 2019-04-14 11:17
You should not need to hack the current code to get it to work.  (Famous last words ;)  )
I think either there is some package or python env. issue or perhaps your display setup is causing iohub to fail. 

I checked that the code example in your OP also worked on my 3.6.7 setup

```
from psychopy.iohub import launchHubServer
io = launchHubServer()
```
and it does, so we know it is not something specific to that code snippet which it good.

>> /home/riftkun/.conda/envs/psycho/bin/python3.5 setup.py install

Did the install go smoothly without any errors? There is a lot of output during the setup. 

Can you please confirm you can run non iohub demos from your python setup like:

- psychopy/psychopy/demos/coder/sysInfo.py
- psychopy/psychopy/demos/coder/stimuli/dots.py

>> ImportError: No module named 'Xlib'
>> .
>> So I don't understand the "no module named 'Xlib'" issue being returned.

This does suggest what it says, that the iohub Python process is not able to import Xlib.

If you just do:

```
import Xlib
```

at the start of your test script does it import OK? 

Thanks again.

**Comment by isolver** [comment] 2019-04-14 12:26
@riftguardian, please disregard my last comment. I think I found the issue. If I connect multiple displays then I get the original error you posted. If you use a single display it should be fine.  Sorry for not thinking to ask / try this earlier.

I'll start working on a proper fix for this on Linux now.

Multi-display is handled correctly on Windows; I use that all the time. 

I can not test a multi-display setup on macOS myself given the current HW I have access to. If someone else has a multi-display macOS setup, would you mind trying the launchHub.py demo and report back if it runs OK.

**Comment by isolver** [comment] 2019-04-14 13:29
Just did a pull request that fixes the multi monitor iohub issue on Linux.

Thanks.

**Comment by riftguardian** [comment] 2019-04-15 18:05
Thank you for your help thus far. I am seeing progress - I am now able to import iohub and run io.launchHubServer(), however there seem's to be further issues with xlib when io.quit() is called.

I am more simply running the following:
>from psychopy.iohub import launchHubServer
io = launchHubServer()
keyboard = io.devices.keyboard
io.quit()

Which gives the following:
>Welcome to PsychoPy3!
>v3.1.0
>
>##### Running: /home/riftkun/.conda/envs/psypy3/lib/python3.5/site-packages/psychopy/demos/coder/iohub/test.py #####
>ioHub Server Process Completed With Code:  0
>Error in ioSever.shutdown():
Traceback (most recent call last):
  File "/home/riftkun/.conda/envs/psypytested/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/server.py", line 939, in shutdown
    self._hookManager.cancel()
  File "/home/riftkun/.conda/envs/psypytested/lib/python3.5/site-packages/PsychoPy-3.1.0-py3.5.egg/psychopy/iohub/devices/pyXHook.py", line 245, in cancel
    self._xlib.XCloseDisplay(self._xdisplay)
AttributeError: 'NoneType' object has no attribute 'XCloseDisplay'

**Comment by isolver** [comment] 2019-04-16 11:47
> py3.5.egg/psychopy/iohub/devices/pyXHook.py", line 245, in cancel
> self._xlib.XCloseDisplay(self._xdisplay)
> AttributeError: 'NoneType' object has no attribute 'XCloseDisplay'

It looks like that error is coming from stopping the iohub server, or the call to io.quit(). At this point I can't tell if this error is still because of xlib issues in the setup or an iohub error I have not seen based. It looks like you are able to start iohub now, just not stop it without getting an exception. progress. ;) 

Can you try running the demo:

```
psychopy/demos/coder/iohub/launchHub.py
```

and let me know how that goes? It will test getting a kb event from iohub, which if working means your xlib is likely OK and there is just some race condition in closing the iohub server at the end of the experiment. 

Thanks again.

**Comment by isolver** [comment] 2021-02-11 12:43
closing. can no longer produce any of the errors mentioned in this issue when using the latest master branch source. Tested on Mint Linux 19.1

**Closed by isolver** 2021-02-11 12:43 UTC
