### ISSUE TITLE
Fullscreen toggle in Builder doesn't work

### ISSUE THREAD

**Issue by mirh** [psychopy/psychopy#2436] opened 2019-05-05 13:45 UTC
My educate guess is that the checkbox in the GUI preferences would be supposed to override the experiment-specific setting (because of course you wouldn't want the whole screen to go "full deploying" while you are prototyping). 

Yet it doesn't seem to have any effect.

**Comment by dvbridges** [comment] 2019-05-05 18:13
@mirh , I am not able to reproduce this error on Windows 10 using 3.1.0 developers version. If you toggle full-screen off but do not change your window size, the window appears as full screen, but you can switch between windows e.g., back to Builder. You cannot do this when full-screen is selected.

**Comment by mirh** [comment] 2019-05-05 18:54
I'm talking about the checkbox in "psychopy preferences", not the one in "experiment settings"

**Comment by m-macaskill** [comment] 2019-05-05 21:50
@mirh No, the opposite is true. For PsychoPy and pretty much all other software that has preferences that can be specified at multiple levels (in this case at the application level and at the level of individual folders/experiments), the lower-level (more specific) settings always override the higher-level (more general) ones. i.e. In the application settings you are saying "in general, I want this to be the case", which means you then don't have to keep specifying the same thing for each experiment. If you do specify a particular setting at the experiment level, you're saying "for this particular experiment, I want this to be the case (which might or might not be different from what I usually want)."

**Comment by dvbridges** [comment] 2019-05-05 22:18
If we do want the PsychoPy preferences to provide default settings for new experiments only, I think the settings component could be updated. Currently, the initial full-screen settings for each experiment object are determined by the initial values of the SettingsComponent, set to True by default. So full screen is always True for new experiments.

If Settings Component should be updated to the full screen preferences only on creation of a new experiment, so that the default preferences settings can be overwritten by the user from Experiment Settings, then I think we need to overwrite the default `fullscr` value in the Settings Component init method using prefs. E.g., 

`fullScr = self.exp.prefsGeneral['fullscr']` should be added to:

https://github.com/psychopy/psychopy/blob/63e05e43d6fbce920a3d3fb828f411db6c6e7d92/psychopy/experiment/components/settings/__init__.py#L89-L110

**Comment by mirh** [comment] 2019-05-06 01:23
> In the application settings you are saying "in general, I want this to be the case", which means you then don't have to keep specifying the same thing for each experiment. If you do specify a particular setting at the experiment level, you're saying "for this particular experiment, I want this to be the case

Yes, but the thing is: \*every\* experiment will *always* carry its very own preference. 
And it's not just a random matter of taste of the authors, if I can explain. 

If they'll want to change it, either it means they are doing another experiment altogether, or it is because in that moment they have an entirely different use case (testing it) 

> Currently, the initial full-screen settings for each experiment object are determined by the initial values of the SettingsComponent, set to True by default. 

Oh.. so that was its utility...
I dunno, pretty much a let down in compared to the "allow fullscreen" I had in mind

**Comment by peircej** [comment] 2019-05-09 12:05
My feeling is, if anything, that the setting shouldn't exist in preferences at all, only as a per-experiment setting. I suggest we remove it from the preferences as an option (although we should obviously check that doesn't break anything for a user that has this in their existing prefs)

**Comment by mirh** [comment] 2019-05-09 13:39
If the supposed use case is the one above, it makes sense... Though again, I feel like "whatever I the developer wants now" and "however the experiment is supposed to run" are two independent things.

**Comment by peircej** [comment] 2019-05-09 14:35
When preferences change the way an experiment runs it can lead to confusing issues for the scientist (e.g. the experiment worked as expected in the office but doesn't work in the lab - or it worked one day in the lab but one of the other lab members changed a preference and now nothing works). So unless it's really necessary we should not allow that to happen (and I regret settings where it does, like the option to set an application preference for stimulus units)

I think this one is resolved so closing

**Closed by peircej** 2019-05-09 14:35 UTC
