### ISSUE TITLE
TextBox/TextStim: premature detection of syntax errors in text field

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3903] opened 2021-06-03 19:25 UTC
Typed code in the text field of textStim and textBox objects are prematurely detected as syntax errors, meaning that input will not be accepted (OK is greyed out). Start typing `$int(random()*10)` the error "python syntax error field `text` : in" will appear in red and block selection of the OK button before the whole phrase is complete. Note that typing the whole phrase elsewhere and copying it in does not produce an error. Windows OS only tested.

**Comment by TEParsons** [comment] 2021-06-04 08:31
This extends to all components - the problem is that once the validator finds one error, it stops looking, so once you fix the error it doesn't recognise that it's fixed.

**Comment by peircej** [comment] 2021-06-08 14:43
fixed in GH-3935

**Closed as completed by peircej** 2021-06-08 14:43 UTC
