### ISSUE TITLE
proposal: "duration (loops)" for sound and video files

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#802] opened 2015-01-24 03:11 UTC
A natural thing to want to do is play a sound or movie clip for the duration of the file. It might be worth the (small?) effort to add support for duration to be specified in terms of loops through the media file, with the default being 1.

This would allow auto-terminating a routine when a sound ends.

**Comment by peircej** [comment] 2015-01-24 15:04
This wasn't a proposal as such. It was always intended behaviour and *used to be* the behaviour until the switch to loop a short section of tone to create variable-length tones. I think this is fixed now

**Closed by peircej** 2015-01-24 15:04 UTC
