### ISSUE TITLE
PsychoPy3 Error on mac -- crash on opening after new install

### ISSUE THREAD

**Issue by jennifer-culbertson** [psychopy/psychopy#1955] opened 2018-08-17 09:37 UTC
Hi,

I've recently installed PsychoPy3 (with Python 3.7). When opening I get this error message:

![screen shot 2018-08-17 at 10 32 52](https://user-images.githubusercontent.com/8694656/44259429-5b999f80-a209-11e8-9793-4e882325ebd8.png)

I've seen a couple of similar issues, but none of the suggested fixes (launch from terminal or use of beta 3.0.0b6 version).

Here is the error log from terminal:

![screen shot 2018-08-17 at 10 33 03](https://user-images.githubusercontent.com/8694656/44259447-694f2500-a209-11e8-879d-dda0748894a5.png)

The result is that the program does not open at all. Any ideas?

Thanks,
-Jenny

**Comment by hoechenberger** [comment] 2018-08-17 09:39
This seems to be a duplicate of #1952. There is no fix yet, as I understand it.

**Comment by jennifer-culbertson** [comment] 2018-08-17 09:42
Thanks, I didn't see that one. Ok, fingers crossed for a fix soon then!

**Comment by peircej** [comment] 2018-08-17 10:00
Definitely a duplicate error. I'm working on a solution and will post on the original issue when I have a fix

**Closed by peircej** 2018-08-17 10:00 UTC
Labels: needs upstream fix, platform mac, standalone & packaging
