### ISSUE TITLE
Undo / Redo behaves strangely in Builder

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2119] opened 2018-11-28 09:14 UTC
![undo-redo](https://user-images.githubusercontent.com/2046265/49141025-f66c4480-f2f5-11e8-82ce-94c6abf03bc5.gif)

This is with `master` on macOS Mojave, Python 3.6.6, PyQt 5.6.0, wxpython  4.0.3.

**Comment by dvbridges** [comment] 2018-11-28 09:58
@hoechenberger, I cannot reproduce this on Windows 10, so specific to macOS with Mojave?

**Comment by hoechenberger** [comment] 2018-11-28 10:14
@dvbridges I believe my colleague @shirllim had the same issue on Windows 10

@shirllim Did this only happen with the development version we run in the lab, or also with the stable standalone on your computer?

**Comment by peircej** [comment] 2018-11-28 10:29
I've just tested on master with 2.7.15 and 3.6.1 (python.org framework installs) and can't reproduce on those. PyQT version is definitely irrelevant (not involved at all in builder interface). I wonder if 3.6.6 is doing something different with copies/references

**Comment by hoechenberger** [comment] 2018-11-28 10:32
If PyQt is irrelevant, this might be more of a wxpython issue then? Currently don't have time to test different package combinations, though (preparing for a conference)

Forgot to add, we're running `conda` installs here – maybe _they_ are doing something odd, too (wouldn't be the first time!)

**Comment by shirllim** [comment] 2018-11-28 10:56
> @dvbridges I believe my colleague @shirllim had the same issue on Windows 10
> 
> @shirllim Did this only happen with the development version we run in the lab, or also with the stable standalone on your computer?

This happen with the development version in the lab (on windows 10). 
Just tested pre-release standalone (PsychoPy 3.0.0b11, windows) - not an issue.

**Comment by hoechenberger** [comment] 2018-11-28 14:53
I just tested with wxpython 4.0.1 (like @dvbridges's), and the error does not occur there. Updated to 4.0.2, error is back. So it seems something in wxpython has changed after 4.0.1.

**Comment by dvbridges** [comment] 2018-11-28 21:48
The problem also extends to Coder. If you attempt to close your first tab, Coder will crash on second click.

**Comment by dvbridges** [comment] 2018-11-29 14:51
@hoechenberger, I have just downloaded the most recent snapshot build of wx (4.0.4) and the Builder undo/redo and pane closing errors found in both 4.0.2 and 4.0.3 have been fixed.

**Comment by hoechenberger** [comment] 2018-11-29 14:59
Nice work! So it’s actually a wxPython bug! We probably should update the dependencies to <= 4.0.1 and >= 4.04 then :)

**Closed** 2018-12-07 10:49 UTC
Labels: bug, builder, needs upstream fix
