### ISSUE TITLE
writing results to csv no longer by trial

### ISSUE THREAD

**Issue by jvcasillas** [psychopy/psychopy#1562] opened 2017-10-16 19:43 UTC
Mac os X. Version 1.85.4 in builder mode.

It appears that psychopy no longer logs results on a by-trial basis, but rather all data are written to the .csv file upon finishing the experiment. Is this expected behavior? Is it possible to adjust this in builder so that responses are written to .csv at the end of each trial?

**Comment by stephanatl** [comment] 2017-10-19 18:45
I'm having the same problem with Mac OS X, Version 1.85.4 in builder mode. Very frustrating.
The .csv file isn't written out if I end the experiment early, but it is written out if I go through the entire experiment. Would much prefer data logging the way it was before (assuming that this is not a bug but a planned change in how the data are logged). In any case, the experiment settings are now misleading because they still appear to give the option to save data trial by trial.

**Comment by hoechenberger** [comment] 2017-10-19 19:39
We'll look into this, thanks for reporting!

**Comment by peircej** [comment] 2017-10-19 19:48
The data files were never being written on each trial - they were written whenever you exited the experiment (but it was still fine to exit halfway through). Presumably it isn't doing this anymore on your experiment. That would be a bug nothing deliberate on our part.

We need to narrow down the occasions when it happens; if you run something as simple as the stroop demo do you get data? If so then we need to work out what is different about your main experiment

**Comment by hoechenberger** [comment] 2017-10-19 19:54
Also, could you please let us know with which PsychoPy versions you still managed to get the expected behavior?

**Comment by jvcasillas** [comment] 2017-10-20 01:04
I am using version 1.85.4 and I can confirm that I do not get the .csv output if I quit the strop task before it finishes. I believe this behavior began with the 1.85.4 update.

**Comment by peircej** [comment] 2017-10-20 12:42
I haven't been able to replicate this issue  with PsychoPy Standalone 1.85.4 on MacOS (10.11) nor on Windows7. 
Not sure what to suggest. I assume you aren't pressing the red stop button?

The only thing I can think of is that the audio lib on your machine is not closing down so the experiment doesn't correctly close itself (and therefore doesn't save the file on close the way it should).

**Comment by hoechenberger** [comment] 2017-10-20 12:52
@jvcasillas @stephanatl How exactly _do_ you end the experiment early?

**Comment by jvcasillas** [comment] 2017-10-20 13:01
I am using the escape key to quit the experiment. Is there a setting I can change regarding the audio lib to try to test?

**Comment by peircej** [comment] 2017-10-20 13:10
In the preferences you can change the audio lib (e.g. set the first entry to be 'sounddevice' or 'pygame' rather than 'pyo'). *BUT* if this were the problem I *think* you'd be pressing Esc and then *also* having to press the red stop button. So I am quite puzzled.

**Comment by stephanatl** [comment] 2017-10-20 14:25
I can confirm that I'm using the latest version (1.85.4 for Mac Os X, in Sierra).  I don't get the problem when I use version 1.84.2. The problem occurs also with the example program (Stroop). I'm using the Esc key to terminate the experiment. When I quit out of the running experiment with Esc it does actually end the experiment and write out a .log and a .psydat file, but no .csv file.

**Comment by jvcasillas** [comment] 2017-10-20 14:51
For the sake of completeness I just did a fresh install of 1.85.4 and still do not get the .csv output (the .log and .psydat are created). I then downgraded to 1.85.2, retested with the stoop task, and I do get the desired behavior (the .csv file is created upon quitting the experiment).

**Comment by CRiddler** [comment] 2017-10-20 18:32
Just two bits of information will help us diagnose this:
* Are you getting some type of error or message written out when you close the experiment early? If so can you please copy and paste it here.
* If you let the experiment run to completion, is it writing out the .csv logs properly?

**Comment by stephanatl** [comment] 2017-10-20 19:03
Here is the error message I get in the output window, which I only get when I close the experiment early:
Running: /Users/stephan/Dropbox/RESEARCHSHARE/PSYCHO1/EMOPIX_BLOCK/EMOPIX BLOCKED JUNKY_lastrun.py 
2017-10-20 14:59:39.551 python[1788:88404] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/8w/xvrzz8gx4tgf_81lttd17w5r0000gr/T/org.psychopy.PsychoPy2.savedState
Exception RuntimeError: RuntimeError('sys.meta_path must be a list of import hooks',) in <bound method ExperimentHandler.__del__ of <psychopy.data.experiment.ExperimentHandler object at 0x1164cb150>> ignored

When I run the experiment to completion the .csv files do write out properly.

This is all with Mac version 1.85.4, which I just did a fresh install with.

**Comment by jvcasillas** [comment] 2017-10-20 19:04
The receive the same output (specific to my file system).

**Comment by CRiddler** [comment] 2017-10-20 19:15
@stephanatl and @jvcasillas good news: I've seen that error before and tracked down the issue! However, since it seems to be a packaging issue, the easiest fix is to step back and use 1.85.2

@peircej I think I've traced down the error. It has to do with the packaging of the 1.85.4 and is a 2 step issue (this was tested and resolved on a fresh install of 1.85.4 on Mac OS)

*psychopy/data.py for some reason exists inside of this version alongside psychopy/data/ so I can't be sure which one psychopy is grabbing when we import. Also data.py does contain the old code that fully relies on the `__del__` method of ExperimetHandler. I deleted data.py and data.pyc since those files shouldn't be in this 1.85.4 (and so I could be sure psychopy would import the folder psychopy/data/ and not the `.py` version. However even with this, the issue still persisted. So there must be an issue inside the psychopy/data/ folder
*inside of psychopy/data/ there are only .pyc files, no .py files which I thought was a little fishy. Specifically I was curious about the experiment.pyc file and that it was the correct version with the `atexit` fix we put out about a month ago. Since I didn't have any tools handy to uncompile the .pyc files to look at what they contained, I copied over the `experiment.py` file from github (with the 1.85.4 tag version) into psychopy/data/ and deleted the old `experiment.pyc` file

Performing both of the above resolved this issue from the standalone package for me, and my psychopy wrote `.csv` files out as expected.

So it seems like we need to remove `data.py` from 1.85.4 standalone packaging and double check that the `experiment.py` file is from the correct version.

**Comment by stephanatl** [comment] 2017-10-20 19:26
OK, good to know that the problem has been tracked down and will be fixed in a later release. I'll go back to 1.85.2 for now. Thanks!

**Comment by cllcpdx** [comment] 2017-12-05 21:53
@CRiddler I'm having the same issue with PsychoPy not writing csv files. I reinstalled the standalone 1.85.4 version for Mac OS X and followed the steps you listed. I deleted data.py and data.pyc from *psychopy/data. I also deleted experiment.pyc in the same folder and added experiment.py from the source code (tar.gz). 

Do you have any other suggestions for modifying 1.85.4? My lab currently has experiments running in this version, and we would prefer not to go back to 1.85.2.

**Comment by CRiddler** [comment] 2017-12-05 22:14
Hm, I just re-tested my patch and it worked again. Just to be sure we're following the same steps:

    * Download 1.85.4 standalone
    * From the standalone package contents- delete
        * `/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/data.py`
        * `/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/data.pyc`
        * `/Users/riddellcd/Desktop/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/data/experiment.pyc`
    * Download and unzip source code from `https://github.com/psychopy/psychopy/releases`
    * Copy `psychopy-1.85.4/psychopy/data/experiment.py` from source code into `PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/data/` folder
    * Open the newly modified standalone psychopy (close first, it if it was open before. Also ensure that you're opening the modified standalone psychopy and not some other psychopy that you've had on your system)
    * Run an experiment and hit the `esc` key at some point and check to see if your data was written successfully. If not, please post the error message.

**Comment by peircej** [comment] 2017-12-06 10:00
I'm pretty close to releasing a 1.86.0 version, which will have the fix included, but maybe it's worth one more bug-fix release in the 1.85 line as well just for this issue (the 1.86 release will include a lot of code refactoring and probably needs a fair bit of alpha testing)

**Comment by cllcpdx** [comment] 2017-12-07 17:55
It's working! Thank you so much. I was initially closing it out with the red 'x', but using 'esc' worked, and all the files were created.

**Closed** 2018-01-09 10:58 UTC
Labels: bug, standalone & packaging
