### ISSUE TITLE
Cannot get audio input to work

### ISSUE THREAD

**Issue by umenge** [psychopy/psychopy#2694] opened 2019-11-27 13:46 UTC
I want to create an experiment in which I record participants. I added the 'Microphone' response type for this, however, whenever I try to run the experiment I get the following error in the console: 
```
    import psychopy.sound.backend_pyo as pyo
AttributeError: module 'psychopy.sound' has no attribute 'backend_pyo'
```
I installed the pyo package, so I'm not really sure what the problem here is?

**Comment by peircej** [comment] 2019-11-28 15:02
What version of psychopy do you have installed? Older versions didn't have it organised this way

**Comment by umenge** [comment] 2019-11-28 15:04
I have version 3.2.4, I think it should be the latest version as I only installed it very recently on this computer...

**Comment by peircej** [comment] 2019-11-28 15:17
And you'r sure nobody else installed another version years ago? People often have multiple python installations and their experiemnt accidentally runs on a different one.
You could do this to check that the path matches what you're expecting, and what python files are contained there:
``` python
import glob
import psychopy.sound
print( glob.glob(psychopy.sound.__path__[0]+"/*.py"))
```

**Comment by umenge** [comment] 2019-11-29 08:15
There's definitely no other PsychoPy installation, though I'm not so sure about the actual Python version... it's possible that I have several installed. Would it help if I completely uninstall Python and re-install it? I used Anaconda to install Python. 

If I run that code snippet, I get the following output: 
`['C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_ptb.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_ptb_BACKUP_20912.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_ptb_BASE_20912.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_ptb_LOCAL_20912.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_ptb_REMOTE_20912.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_pygame.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_pyo.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_pysound.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\backend_sounddevice.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\_base.py', 'C:\\Program Files\\PsychoPy3\\lib\\site-packages\\psychopy\\sound\\__init__.py']`

**Comment by peircej** [comment] 2019-11-29 09:52
OK. I'm not sure why you get an error `'psychopy.sound' has no attribute 'backend_pyo'` when sound/backend.pyo clearly exists, but I still think this is an issue with mixed installations not a bug in PsychoPy.
You say you've installed using anaconda, but the paths you're referring to above are *not* anaconda locations. Those paths have been created from a Standalone PsychoPy installation.
I'm closing this for now but feel free to reopen if new info suggests that it *is* a bug we need to fix in the code rather than a mixed up installation (that you might want to discuss on the forum).

**Closed by peircej** 2019-11-29 09:52 UTC
