### ISSUE TITLE
suggestion for html compiling

### ISSUE THREAD

**Issue by schekroud** [psychopy/psychopy#2865] opened 2020-05-12 16:50 UTC
is it possible to be able to have something where you can add lines to the index.html that is generated when the builder compiles to javascript?

at the moment if you want to use a third party package, or your own functions from a js file, you have to re-insert these lines each time you recompile (just updating the task as you are making it). it would be great if there was a way of specifying exactly what you want to add (in the experiment settings?) and every time you compile to it these lines are added automatically.

**Comment by peircej** [comment] 2020-05-12 16:56
Commit 6f2074361eccdfc78150c52e9db6d0ac2b89ed2d did add the option for custom code to be added at the very beginning of the JS script (not the html file) but I think that should suffice for new imports, right?

**Comment by schekroud** [comment] 2020-05-12 18:45
when i tried to import d3 in that way, it wouldn't work. Only managed to get d3 by adding the cdnjs source into the html file, then it's available. Also had issues with functions being made not having global scope (making in one routine at begin expt and the function not being seen by a later routine), and bypassed it by making a separate myfuncs.js that i imported similarly to d3

**Comment by peircej** [comment] 2020-05-12 18:50
again, functions at the ery top of the js (not insdie another function) should have global scope. I'll find out about d3 and whether that should work

**Comment by schekroud** [comment] 2020-05-12 19:25
ah, sorry for the confusion. I just checked the code from that commit and get what you mean. I don't have the as an option on code components though. has this been packaged into a release?

thanks for this though!

**Comment by peircej** [comment] 2020-05-12 19:29
No that commit was just a few days ago, meaning I *think* your request is completed but not yet released. If your code can in fact be added to the very top of the JS file (outside the first function) then I think we can closed the issue

**Comment by peircej** [comment] 2020-06-20 19:23
This will be in release 2020.2 and I believe the issue is then fixed but reopen if it doesn't address your needs

**Closed by peircej** 2020-06-20 19:23 UTC
