### ISSUE TITLE
TextBox broken?

### ISSUE THREAD

**Issue by glupyan** [psychopy/psychopy#1790] opened 2018-04-05 02:53 UTC
See https://discourse.psychopy.org/t/textbox-broken/4202

**Comment by peircej** [comment] 2018-04-24 09:34
I'm not seeing this problem on the Standalone installations of 1.90.1 so either it's something that has been fixed or it's a problem with the anaconda installation.

**Comment by hoechenberger** [comment] 2018-04-25 03:09
Working for me with a conda installation (Python 2.7) on macOS with latest stable. @glupyan, can you try again with the latest PsychoPy release?

**Comment by hoechenberger** [comment] 2018-05-29 09:41
Closing, cannot reproduce.

**Closed by hoechenberger** 2018-05-29 09:41 UTC
Labels: Anaconda, waiting for feedback
